### ISSUE TITLE
Error occurred! 

### ISSUE THREAD

**Issue by f1refa11** [PranshulGG/WeatherMaster#10]
![Screenshot_20240827-093617_WeatherMaster.png](https://github.com/user-attachments/assets/fa5cc60a-2d42-4aa2-8e9b-bbb9b3c966f0)

any idea why this might be happening?

**Comment by PranshulGG** [comment]
> any idea why this might be happening?

There's an issue with the data being requested when the app loads. It will be fixed in the next version.
