### ISSUE TITLE
Blend the line below clouds

### ISSUE THREAD

**Issue by sarojpanda44** [PranshulGG/WeatherMaster#100]
If possible it would be nice to blend the top border of the Frog image with the weather animation. Check Google weather for reference.
![Screenshot_20241026-210237](https://github.com/user-attachments/assets/1a2c0b47-af5c-42bf-8b34-d7d068bffd0c)

Google weather 
![Screenshot_20241026-210419](https://github.com/user-attachments/assets/e9a0c7e2-c33c-4129-ae14-c448a1e87307)

**Comment by PranshulGG** [comment]
Yep, I have improved the animations for the next release.
