### ISSUE TITLE
Add Multiple Weather Providers

### ISSUE THREAD

**Issue by PranshulGG** [PranshulGG/WeatherMaster#102]
I'm considering adding support for multiple weather providers to give users the flexibility to switch between providers in the app settings. The app will primarily use the selected provider for weather data, but if specific data is missing from the provider, it will automatically fetch the missing information from other APIs.
 
### Planned Weather Providers:
- MET Norway
- Open-Meteo
- AccuWeather
- WeatherAPI
- OpenWeather (optional)

### Notes:

- Suggestions for other reliable weather providers are welcome.
- If anyone has experience working with these APIs, feedback and recommendations would be helpful.

**Comment by ak47m91** [comment]
Met norway and open meteo will have an api key provided by the app?

**Comment by PranshulGG** [comment]
@ak47m91 They don't need one 😉

**Comment by ak47m91** [comment]
What abt open weather, will the app come with an api key?

**Comment by PranshulGG** [comment]
> What abt open weather, will the app come with an api key?

Yeah, it comes with a default key, but you have to use your own if you want more calls. The free API limit is 1,000 calls per day.

**Comment by ak47m91** [comment]
So one call is for one location or for the entire world?

**Comment by PranshulGG** [comment]
https://openweathermap.org/api/one-call-3 

>for the entire world?

**Comment by PranshulGG** [comment]
By 'one call,' I mean it returns all the data in a single API call.

**Comment by ak47m91** [comment]
So it could work, setting an api call once every 10 min

**Comment by PranshulGG** [comment]
What do you mean?

**Comment by ak47m91** [comment]
So for the entire world one call, there are 24 hours multiplied by 60 minutes and it is equal to 1440. If there are 1000 calls per day, then one call every 10 minutes should be more than enough

**Comment by PranshulGG** [comment]
Yeah, but its the same api key for everyone

**Comment by ak47m91** [comment]
Yeah

**Comment by PranshulGG** [comment]
So, for anyone not using their own API key, the calls will be sent using the default key. The 1,000-call limit will quickly run out.

**Comment by ak47m91** [comment]
How ? One call every 10 min means  the calls should not run out

**Comment by PranshulGG** [comment]
Yeah, but if the key is the same, the calls will still go through. Weather updates every 10 minutes, but that doesn’t mean we can’t send calls. If there are 1,000 users and each makes a call, the limit will run out quickly, especially if you’re also searching for locations and other data.

**Comment by PranshulGG** [comment]
> Ahh, I understand, I think it's better to have OpenWeatherMap with an user provided api key

Yeah, then that's going to work the way you're saying.

**Comment by ak47m91** [comment]
For accuweather we had no other choice

**Comment by PranshulGG** [comment]
> For accuweather we had no other choice

Yeah, XD. I still don't know exactly how Breezy Weather is using it.

**Comment by Stzyxh** [comment]
How about adding Geosphere Austria.

[Geosphere Austria Data Hub](https://data.hub.geosphere.at/) 
[API Docs] (https://dataset.api.hub.geosphere.at/v1/docs/)
