### ISSUE TITLE
The rain effects look not like real

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#103]
## UI/UX Issue
The rain effects look not like real.

### Screenshots
![IMG_20241027_094310](https://github.com/user-attachments/assets/d30958b4-94ad-4bde-b0c7-7f314f46a93c)
![IMG_20241027_094223](https://github.com/user-attachments/assets/1ec09c54-1924-480b-8d21-8c3c3b0507a9)

### Additional Context
It should have effects comparable to those of Google Weather.

**Comment by PranshulGG** [comment]
@Tuan1-2-3 Yeah, some of the animations are made in Canvas because I couldn’t find the ones Google is using. It’s only the rainy animation for now, but I’ll try to replicate the same effects. All the other animations are the ones Google is using.

**Comment by Tuan1-2-3** [comment]
OK. I see. It looks like you have a rain effect behind the Frogie picture.
