### ISSUE TITLE
Change the app name in the launcher

### ISSUE THREAD

**Issue by egoravsharma** [PranshulGG/WeatherMaster#106]
Kudos to you for developing an exceptional weather app! The features, UI, and logo all are outstanding. I'm eager to know about the widget's progress, which was announced 2-3 months ago. Do you have an estimated release date for this feature?

Also, I'd suggest changing the app launcher name to simply 'Widget.' This will give it an official weather app vibe that resonates well with the general public.

**Comment by PranshulGG** [comment]
Thanks for the kind words, glad you liked it! Widgets will come in either 1.7.7 or 1.7.8, depending on if I can solve the issue. The app’s coded in JS, so managing widgets and all that background stuff is kinda tricky.

> Also, I'd suggest changing the app launcher name to simply 'Widget.' This will give it an official weather app vibe that resonates > well with the general public.

you mean change the app name?

**Comment by sarojpanda44** [comment]
Honestly I didn't like this idea. Your app name is unique and should keep the name to distinguish in the launcher.
The launchers do have option to customize the apps name and icons and users can rename the apps to their desire.
It would be nice to see your original app name in the launcher.

![Screenshot_20241111-215716](https://github.com/user-attachments/assets/9ec04e78-a149-4462-adac-41661396fc11)
