### ISSUE TITLE
14 day forecast not working

### ISSUE THREAD

**Issue by DonTMover** [PranshulGG/WeatherMaster#108]
## Bug Description
A clear and concise description of the issue.

### Steps to Reproduce
Watch the [video](https://youtu.be/V0VahuefSLo)

### Expected Behavior
Opening section with weather for the next 14 days

### Actual Behavior
Contacts are not working

### Environment
- OS: Android 14
- App version: 1.7.6
- Device: Asus Zenfone 10
- Browser (if applicable): -

### Additional Context
-

**Comment by PranshulGG** [comment]
@DonTMover Click on the forecast item, not the container—'cause the container isn’t clickable.

**Comment by DonTMover** [comment]
Well, really, I just thought there should be a vertical list with the weather for the next two weeks.

**Comment by DonTMover** [comment]
Well, really, I just thought there should be a vertical list with the weather for the next two weeks.
