### ISSUE TITLE
Open Meteo as provider?

### ISSUE THREAD

**Issue by ak47m91** [PranshulGG/WeatherMaster#11]
What about open meteo as a secondary provider to chose from or maybe add another so we can have 3 options

**Comment by PranshulGG** [comment]
> What about open meteo as a secondary provider to chose from or maybe add another so we can have 3 options

I've added Open Meteo for some data. Offering a choice between providers would require significant code changes, so I can't promise it, but I'll try

**Comment by ak47m91** [comment]
No problem , but I have one another little improvement. So to me it shows awareness.... type... . So I wondering If you could yust write 
          Weather Alerts , tap to see them, 
then users would click on the button and then see the description

**Comment by PranshulGG** [comment]
> No problem , but I have one another little improvement. So to me it shows awareness.... type... . So I wondering If you could yust write Weather Alerts , tap to see them, then users would click on the button and then see the description

So you mean that instead of writing the title of the alert, I should use **Weather Alerts - tap to see them**? If that's the case, I can do that. Thanks for the feedback

**Comment by ak47m91** [comment]
Like this maybe
![Screenshot_20240827_115928_WeatherMaster.jpg](https://github.com/user-attachments/assets/d9c2ee2c-e7f8-4220-9511-d1b7633bf990)

**Comment by ak47m91** [comment]
And them in the next screen list the alerts

**Comment by PranshulGG** [comment]
Got it! I'll update it in the next version

**Comment by ak47m91** [comment]
Sorry to ask but what should this mean?

**Comment by PranshulGG** [comment]
> Sorry to ask but what should this mean?

to display the awareness level and type, similar to what I see in the screenshot

**Comment by ak47m91** [comment]
Well that's what it shows me![Screenshot_20240827_124106_WeatherMaster.jpg](https://github.com/user-attachments/assets/0c18c017-3fc6-40d5-9604-91e6b65c6635)

**Comment by ak47m91** [comment]
I think it's from open weather map

**Comment by PranshulGG** [comment]
> I think it's from open weather map

These alerts come directly from governments, so the title of the alert cannot be changed. It’s determined by the sender, so there’s nothing I can do about it😐

**Comment by PranshulGG** [comment]
If you're still confused, could you please explain further ?

**Comment by ak47m91** [comment]
Well bruh, thank to the goverment

**Comment by PranshulGG** [comment]
> Author

XD

**Comment by PranshulGG** [comment]
Alerts can vary depending on your country, location, and the way they are sent.

**Comment by ak47m91** [comment]
Hello again, sorry to be a burden , but I have some suggestions 
First, I suggest moving the moderate risk and fair to the right because there is dead space there and it helps saving space

![Screenshot_20240830_144153_WeatherMaster.jpg](https://github.com/user-attachments/assets/f7f10fe5-8648-4f1c-88f4-da0ad1b529f4)

Then you could use some of the shapes of the new Google Weather app for the visibility,  humidity,  wind and pressure 



![Screenshot_20240830_150055_WeatherMaster.jpg](https://github.com/user-attachments/assets/31b54891-99dc-49c3-a344-951da63954a7)

![Screenshot_20240830_145011_Pixel Weather.jpg](https://github.com/user-attachments/assets/da429570-c3a9-42c0-a389-f856dc5da4a5)

 That's it , hope you understand my design choices!😀
