### ISSUE TITLE
Minor ui siggestion

### ISSUE THREAD

**Issue by M4rti21** [PranshulGG/WeatherMaster#112]
I just noticed that when swiping throught this pannels there is no horizontal gap in between,it'd be nice if they were to use the samme padding all the pannels have between eachother
![Screenshot_20241112-232753](https://github.com/user-attachments/assets/b6369285-4a1c-4e9d-860e-d42cd24e18ed)

**Comment by PranshulGG** [comment]
The gaps probably won’t work—they’ll mess up the UI by pushing everything to the left and cutting stuff off. Adding them doesn’t make sense since everything fits the space perfectly.

**Comment by M4rti21** [comment]
mhm.. i guess that makes sense :+1:
