### ISSUE TITLE
Add the ability to display atmospheric pressure in `mmHg`

### ISSUE THREAD

**Issue by Korb** [PranshulGG/WeatherMaster#113]
In my country, weather forecasts always expressed atmospheric pressure in millimeters of mercury. I know that at my latitude the normal pressure is 760 mm Hg, and I, like most people in my country, have no idea how much this is in bars, millimeters / meters of water column, kilograms per square centimeter or technical atmospheres. For me, indicating pressure in other units in the application is worse than not having pressure in the application at all.

**Comment by PranshulGG** [comment]
mmHg is already available in the app. Please check the settings.

**Comment by Korb** [comment]
Apparently I made this note to myself before this improvement was implemented. Thanks!
