### ISSUE TITLE
Add the ability to display wind speed in m/s

### ISSUE THREAD

**Issue by Korb** [PranshulGG/WeatherMaster#114]
In my country, weather forecasts always expressed wind speed in m/s. And I find it difficult to quickly answer how much, for example, 6-8 m/s in kilometers per hour or miles per hour (the only options offered by the application)?

**Comment by PranshulGG** [comment]
@korb M/s is also available. You can change the units to your preference in the settings.

**Comment by VasilisKos** [comment]
Beaufort unit would be great too.
