### ISSUE TITLE
Not able to switch back to current location

### ISSUE THREAD

**Issue by sarojpanda44** [PranshulGG/WeatherMaster#116]
After selecting the saved location, I'm unable to select the current location. 
I'm trying to click the Current location and also the location icon in the screenshot. Is there some other way to reset the location to device location? 
![Screenshot_20241115-032642](https://github.com/user-attachments/assets/2a93c759-1a6e-492a-84ec-2e1130ec5d27)

**Comment by PranshulGG** [comment]
The way the current location is saved changed—it’s now done with lat/lon. The old location data might be causing the issue, so the only fix is to clear the app data.

**Comment by sarojpanda44** [comment]
No. Nothing happens. Selecting the other location sets it as current location and no option to reset to default.
![Screenshot_20241115-055808](https://github.com/user-attachments/assets/28d1d35b-1344-450b-bdb9-4fba0092d63f)
![Screenshot_20241115-055821](https://github.com/user-attachments/assets/0d128dac-e28a-40e8-af5c-cdd36b240f1d)

**Comment by PranshulGG** [comment]
Guess I messed something up in this version. I’ll check it out and see what the issue is, then maybe push a hotfix

**Comment by sarojpanda44** [comment]
Issue is fixed. But has minor issue with the location name when selecting the Current location.
![Screenshot_20241115-202434](https://github.com/user-attachments/assets/6ffa8452-979c-4445-aecb-0bb6ca76ebc9)

**Comment by PranshulGG** [comment]
Not sure if it’s an issue, but it might be caused by old app data. Try clearing the app data to fix it.

**Comment by sarojpanda44** [comment]
Have cleared all storage and cache data and tried again. Same result

**Comment by PranshulGG** [comment]
Well then, that’s your device and how it’s returning your geo location.

**Comment by sarojpanda44** [comment]
That's strange. I thought it's the variable name or something that's displayed.
It should at least display Current location and not "CurrentDeviceLocation"

**Comment by PranshulGG** [comment]
I'll try to fix if it's fixable
