### ISSUE TITLE
Display weather for all saved locations

### ISSUE THREAD

**Issue by sarojpanda44** [PranshulGG/WeatherMaster#117]
Can you fetch the weather forecast for all saved locations on every refresh and display the forecast with weather icons for saved locations?
Currently the app shows precision icon and no weather info for saved locations.
![Screenshot_20241115-055808](https://github.com/user-attachments/assets/605ba99d-27db-4dd2-9e35-b046160a5e11)

**Comment by PranshulGG** [comment]
Like this?

![Screenshot_20241115-083116.png](https://github.com/user-attachments/assets/97958523-6550-43d9-8e8a-1155683b9b80)

**Comment by sarojpanda44** [comment]
Yes. The saved locations should look like this.

**Comment by PranshulGG** [comment]
done!
