### ISSUE TITLE
Translate day summary

### ISSUE THREAD

**Issue by Bobesz57** [PranshulGG/WeatherMaster#120]
Hello, 
I use Hungarian language for the app, but the full day overlook is still in English. I would be very thankful if it would be in my language also.
![Screenshot_2024-11-15-15-21-20-882_com example weathermaster](https://github.com/user-attachments/assets/a7ddfcc4-4ac5-48a0-a07f-d49562b99e5f)

**Comment by PranshulGG** [comment]
What app version are you using.

**Comment by Bobesz57** [comment]
The newest 1.7.9 (W)

**Comment by Bobesz57** [comment]
The newest 1.7.9 (W)> What app version are you using.

**Comment by PranshulGG** [comment]
> The newest 1.7.9 (W)

Well, right now there’s no one to translate it into Hungarian. If you want to help out, you can, otherwise you’ll have to wait.

**Comment by Bobesz57** [comment]
I'm happy to help

**Comment by PranshulGG** [comment]
> I'm happy to help, how can I?

 These sentences are made by joining different ones to create a summary based on the day’s condition. There’s no easy way to add translations to them right now, but if I find a solution, I’ll let you know, and after that you can send a pull request.
