### ISSUE TITLE
The "Sun" box, when expanded, does not look good.

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#124]
## UI/UX Issue
The "Sun" box option, when expanded, does not look good.

### Steps to Reproduce
1. Click on 'Sun'
2. The colour is all pink.

### Expected Behavior
It must have the same colour as the other boxes like yellow, blue, ...

### Actual Behavior
It only has a pink colour

### Screenshots
Having errors when uploading the images 😁😁😁

**Comment by Tuan1-2-3** [comment]
I don't understand what you say 😅😅😅. I think it would look fantastic if you could make that adjustment! Thank you!

**Comment by PranshulGG** [comment]
No problem, I’ll see if it’s possible.
