### ISSUE TITLE
Please add The Weather Channel

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#125]
## Feature Request
Could you please add The Weather Channel provider? That would be awesome, thank you!

**Comment by PranshulGG** [comment]
I read their documentation, and it's not free; you need to provide your own API key. If you're using your own, I can add it for you.

**Comment by Tuan1-2-3** [comment]
OK! While I don't have my own API key, feel free to add it for anyone who has already purchased one. Thanks!
