### ISSUE TITLE
Show the current address in the address bar

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#129]
### Problem Statement

Could you please enter the current address in the address bar? This will make it much easier to locate the current location.

### Proposed Solution

Show the current address in the address bar

### Additional Context

![IMG_20241117_203341](https://github.com/user-attachments/assets/5324a14e-fbea-4742-92ca-58717f75dfbc)
![IMG_20241117_203524](https://github.com/user-attachments/assets/6afa9ff0-b393-4c39-bc39-b34892400a9b)
![IMG_20241117_203726](https://github.com/user-attachments/assets/f7cbbc18-bda6-4f00-84b1-107bf3f7ee4f)
![IMG_20241117_203627](https://github.com/user-attachments/assets/4605511a-5351-421d-a68b-3311853cc5d1)

**Comment by PranshulGG** [comment]
Not possible for now since the API doesn’t support reverse geocoding. I'll have to see if i can find a better free API

**Comment by Tuan1-2-3** [comment]
OK! I don't need that now.😁

**Comment by fparri** [comment]
Would it be possible to use Nominatim APIs?

**Comment by PranshulGG** [comment]
> Would it be possible to use Nominatim APIs?

@fparri  Unfortunately, making it work would require significant changes, like adjusting caching behavior and how locations are saved. I also want to avoid introducing more bugs. However, I’m considering adding a feature to display the device location on the locations page instead.
