### ISSUE TITLE
Home screen widgets

### ISSUE THREAD

**Issue by deanveloper** [PranshulGG/WeatherMaster#130]
It'd be very nice to have a home screen widget similar to the ones provided by googles weather app!

**Comment by PranshulGG** [comment]
duplicate #15

**Comment by deanveloper** [comment]
ah sorry, thought I looked through existing issues but didn't see it 🤦

**Comment by PranshulGG** [comment]
> ah sorry, thought I looked through existing issues but didn't see it 🤦

Yeah, they still need some work. I was busy with the notifications, so it got delayed.
