### ISSUE TITLE
The rain effect doesn't look good

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#131]
### Describe your issue

The rain effect doesn't look as good as the effect in the Google Weather app. Exactly the water splash effect.

### Steps to reproduce

On the home page.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/d38893a0-4ec4-4903-a2ad-c6fa8f577c55

https://github.com/user-attachments/assets/1bb55318-4025-4af6-92a0-d8ffd47b56a6

**Comment by PranshulGG** [comment]
Unfortunately, this can’t be changed. For one, Google only has one froggy image for rainy weather, while my app has like 10 of them.

**Comment by Tuan1-2-3** [comment]
OK!
