### ISSUE TITLE
The pressure page doesn't show correctly

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#135]
### Describe your issue

The pressure page doesn't show correctly (Version 1.8.2)

### Steps to reproduce

1. Click on 'Pressure'
2. See the issue

### Put here any screenshots or videos (optional)

![Screenshot_2024-11-19-20-14-49-113_com example weathermaster](https://github.com/user-attachments/assets/0bb49307-c1bc-4d83-8e13-90426527a3d8)
![Screenshot_2024-11-19-20-14-52-203_com example weathermaster](https://github.com/user-attachments/assets/4c96213a-eb83-4244-85bb-9b7bf755be8b)

**Comment by PranshulGG** [comment]
- This is working as intended:

1. The page uses the current hour forecast, not the 15-minute one.
2. The difference is minimal—just a few values that don’t really impact the overall experience.
3. This is the best it can get unless I switch to a different data source.
