### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Stzyxh** [PranshulGG/WeatherMaster#137]
App crahes when I try to open it. Tryd reinstalling but didn't work. Im on
 Android 13
Fairphone 4
1.8.2

**Comment by PranshulGG** [comment]
Did you tried clearing the app data?

**Comment by Stzyxh** [comment]
> Did you tried clearing the app data?

Yes and reinstalled it

**Comment by cust0muser** [comment]
Yes I also cleared cashe

**Comment by PranshulGG** [comment]
Found the issue! I’ll release a new version in about 30 minutes.

**Comment by PranshulGG** [comment]
fixed in 1.8.3
