### ISSUE TITLE
Taking too long to load weather into after a day or so unable to use it continuously.

App UI looks nice.

I'm using Samsung s23 ultra. 

Also tried clearing the cache and data

### ISSUE THREAD

**Issue by penguinkb** [PranshulGG/WeatherMaster#14]
![Screenshot_20240830_073443_WeatherMaster.jpg](https://github.com/user-attachments/assets/ccdc80b1-0e00-4bb6-88a5-343ca58d58a1)

**Comment by PranshulGG** [comment]
It's an issue with how it calculates the time zone, which sometimes gives an error. It's going to be fixed in the next version. Thanks for the feedback!
