### ISSUE TITLE
UI Enhancement Proposal: Improve Precipitation & Temperature Display

### ISSUE THREAD

**Issue by obakha** [PranshulGG/WeatherMaster#141]
### Describe your issue

I would like to suggest some UI improvements to enhance the usability and visual clarity of the app. After comparing the current design with my proposed enhancement (see screenshots below), I believe these updates could significantly improve the user experience, especially for precipitation and hourly forecast details.

## Proposed Enhancements  
1. **Enhanced Hourly View:**  
   - **Current Observation:** The hourly forecast for precipitation and temperature is displayed but lacks integration and emphasis, making it less intuitive to interpret at a glance.  
   - **Suggestion:** Adopt a design similar to the uploaded "Proposed Enhancements", where precipitation, temperature, and timing are better aligned visually for ease of comparison.

2. **Precipitation Details:**  
   - **Current Observation:** The app does not currently highlight precipitation starting times, which are critical for users planning their activities.  
   - **Suggestion:** Introduce details such as “Rain starting in X minutes”, along with corresponding visual cues to make this information accessible and actionable.

3. **Graphical Representation:**  
   - **Current Observation:** The temperature and precipitation probabilities are shown as text without strong visual indicators.  
   - **Suggestion:** Integrate graphical indicators (e.g., bar charts, gradient shading) to make trends more apparent while maintaining simplicity.

### Steps to reproduce 

1. Open the WeatherMaster application.  
2. Navigate to the **Current Weather** and **24-Hour Forecast** screens.  

![Current Weather](https://github.com/PranshulGG/WeatherMaster/raw/master/preview/current.png)

![24-Hour Forecast](https://github.com/PranshulGG/WeatherMaster/raw/master/preview/24hr.png)

3. Observe the current display of hourly forecasts, precipitation probabilities, and temperature trends.  
4. Note the lack of precipitation start times, and integrated graphical representations.  
5. Compare with the proposed design in `Proposed Enhancements` for clarity and usability improvements.

### Put here any screenshots or videos (optional)

 **Proposed Enhancements:**  
   - ![Enhanced Layout 1](https://i.ibb.co/zQ0yrWT/8d7f51bf-8eae-418f-acfe-43248f641c96.jpg)  
      - ![Enhanced Layout 2](https://i.ibb.co/LZsCqb9/3458e600-d608-4e48-b0e3-554ed9b4942e.jpg)  
   - ![Enhanced Layout 3](https://i.ibb.co/12tHVBG/cc32fb65-7a82-42df-9534-51d67599a25e.jpg)  
      - ![Enhanced Layout 4](https://i.ibb.co/gwfcgcx/44ee1f65-aad2-4235-af9d-e32965b6a830.jpg)

**Comment by PranshulGG** [comment]
Adding an "When Is rain about to start" option is a good idea, but I'd much prefer to use this type of tile:

![WhatsApp Image 2024-11-20 at 8 57 53 AM](https://github.com/user-attachments/assets/61876312-34de-40ac-93f7-4f6889acdf07)

**Comment by obakha** [comment]
Yes, sorry for the bad designs, I just edited some screenshots on top of your UI, the one you mentioned is actually great, I'm looking forward to how it'll turn out.
