### ISSUE TITLE
The sunny effect on the About page has been lost.

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#144]
### Describe your issue

The sunny effect on the About page has been lost.

### Steps to reproduce

1. Go to 'Setting'
2. Swipe down and click on 'About Weather Master'
3. See the issue

### Put here any screenshots or videos (optional)

![IMG_20241120_053926](https://github.com/user-attachments/assets/7e66c8cd-d8c7-4ea7-a308-45823698cb50)

**Comment by PranshulGG** [comment]
The effect wasn't looking that good so it was removed.
