### ISSUE TITLE
Scrolling through weather recommendations

### ISSUE THREAD

**Issue by DonTMover** [PranshulGG/WeatherMaster#146]
### Describe your issue

You just can't scroll with a simple swipe

### Steps to reproduce

1.Watch the [video](https://youtube.com/shorts/5t8hzSb6XPY) to see the problem

**Comment by PranshulGG** [comment]
Will be fixed in 1.8.5!

**Comment by Tuan1-2-3** [comment]
The "pull to refresh" affects that. If you scroll carefully to the left, it will work. I have met that issue this morning. Or I can use the dots under the weather recommendations.

**Comment by Tuan1-2-3** [comment]
But for any reason, if possible, it would be great if you could take care of that issue. Thank you!

**Comment by PranshulGG** [comment]
> The "pull to refresh" affects that. If you scroll carefully to the left, it will work. I have met that issue this morning. Or I can use the dots under the weather recommendations.

its due to some faulty code that's creating an empty, invisible container. This issue only seems to occur around sunrise or sunset.
