### ISSUE TITLE
Add widget

### ISSUE THREAD

**Issue by wlUnUlw** [PranshulGG/WeatherMaster#15]
This app great but it still missing widget

**Comment by PranshulGG** [comment]
I do plan to add widgets soon, but it's just too complicated. 😖

**Comment by wlUnUlw** [comment]
It's understandable, I hope this feature will be added soon

**Comment by pdimu** [comment]
The Google weather widget with Material Design would be great

**Comment by pdimu** [comment]
Examples
Pixel Weather Widget app:
https://play.google.com/store/apps/details?id=twelve.weather.mibrahim
Original Weather Widget 
![RDT_20240830_2115501057067467729945444.jpg](https://github.com/user-attachments/assets/40bd47a1-7db7-409e-a83c-3fd2d99cd3a3)
https://images.app.goo.gl/eBaV8SqbJQ8DtcCx6

**Comment by PranshulGG** [comment]
I'm working on the widgets but got stuck with background activity issues because Android keeps destroying it. I need to watch some tutorials, but the widgets will be available in the next few days.

**Comment by Tuan1-2-3** [comment]
Wow! I'm excited about it—it's going to be amazing! 😊

**Comment by Tuan1-2-3** [comment]
But it looks not good:
1. The font is ugly
2. Doesn't have Material You colour like the one of Google Pixel.

[Screenshot_2024-11-28-20-06-48-316_ginlemon.flowerfree-edit.jpg](https://github.com/user-attachments/assets/17193aeb-eacf-4e79-9846-7f95de3af653)
