### ISSUE TITLE
German translation not consistent

### ISSUE THREAD

**Issue by formeo14** [PranshulGG/WeatherMaster#151]
### Describe your issue

Hello,

I recently noticed that the German translation in the application is not consistent across all sections. Some parts of the application have been translated correctly, while others are still in English. This inconsistency can be confusing for German-speaking users and may affect the overall user experience.

I would be happy to contribute by providing the missing translations for the German language. Here are the specific areas where the translation is inconsistent or missing:
 In the main menu, settings, humidity, Sun, visibility, summary ...

### Steps to reproduce

1. Open the app. Change language to German

### What was the expected result?

Using German language for most of the UI elements

### Put here any screenshots or videos (optional)

![Screenshot_20241124-130442_Weather Master](https://github.com/user-attachments/assets/80b4f279-3bb4-45e7-b602-a4206b0eef7d)
![Screenshot_20241124-130418_Weather Master](https://github.com/user-attachments/assets/1b07a03e-2cd8-4c0d-8335-fff5b66429f2)
![Screenshot_20241124-130521_Weather Master](https://github.com/user-attachments/assets/a66264e9-64b0-4861-bd8f-31857ff1b571)
![Screenshot_20241124-131321_Weather Master](https://github.com/user-attachments/assets/b3eb54bb-b8ab-4822-b2c9-4e4b2d70d8dc)

**Comment by PranshulGG** [comment]
@formeo14 I think there are problems with trying to maintain translations for an open source project in multiple languages.

At some point, we might need to update the English content on the app or add new content. This means we’d also need a German translator to update the German version. However, if the original translator is no longer available or interested, we’re stuck. The German version of the app could then either fall out of sync with the English version over time or have more and more sections replaced by English text.

And right now the strings aren't updated.

**Comment by formeo14** [comment]
@PranshulGG  As said I would like to help providing the missing translations. But do you use Weblate or how should the localized text be provided?

**Comment by PranshulGG** [comment]
> @PranshulGG As said I would like to help providing the missing translations. But do you use Weblate or how should the localized text be provided?

> And right now the strings aren't updated.

I need some time to update the strings because there are too many due to the growth of the codebase and additional features. Some of the generated text can’t be translated properly since it’s composed of dynamic pieces rather than fixed content.

**Comment by formeo14** [comment]
Take your time if many of the texts are not dynamic with translation files but static just static strings. Just write when that is done. I'll be happy to add the German translation.
The generated text can certainly be generated dynamically in the respective language, but that will probably take even more time.
So take your time, it is not of high priority but would be great.

**Comment by PranshulGG** [comment]
> Take your time if many of the texts are not dynamic with translation files but just static strings. Just write when that is done. I'll be happy to add the German translation. The generated text can certainly be generated dynamically in the respective language, but that will probably take even more time. So take your time, it is not of high priority but would be great.

Yeah, the function that generates text is usually created by me without using any external services. I don’t think I can make it work for other languages, as I have no knowledge of how to do that.

**Comment by formeo14** [comment]
Youu updated the `langs.js` file! Thank you.

The translations are now much more consistent, but there are still some static values missing, and almost every dynamic string needs a way to be localised.
