### ISSUE TITLE
The rain expectations are always showing with a blank box

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#156]
### Describe your issue

It seems that the rain forecasts often show a blank box, even on days when it won’t be raining. Isn’t that a bit confusing?

### Steps to reproduce

It is on the homepage

### Put here any screenshots or videos (optional)

![IMG_20241125_124229](https://github.com/user-attachments/assets/3e35e7d8-9501-4fe7-82ad-76b341ad5ddc)

**Comment by PranshulGG** [comment]
This is a timing bug; it's usually hidden. The next update will focus on fixing bugs like this.
