### ISSUE TITLE
Add more map

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#157]
### Problem Statement

Could you add a wind speed map, a temperature map, and a severe weather map, just like the ones in Apple's weather app? That would be awesome!

### Proposed Solution

In the map option it will have 4 maps:
1. Rain map
2. Temperature map
3. Severe weather map
4. Wind speed map

**Comment by PranshulGG** [comment]
@Tuan1-2-3 This likely won't be implemented as there's no free API available that provides these layers.

**Comment by Tuan1-2-3** [comment]
OK.
