### ISSUE TITLE
Search Bar Not Functioning Properly

### ISSUE THREAD

**Issue by itz-rj-here** [PranshulGG/WeatherMaster#159]
### Describe your issue

Hi there,
I encountered an issue with the search bar in your weather app. When I attempted to check the weather manually by entering a location (instead of using GPS), the search bar did not function as expected.

To troubleshoot, I used VPN apps to verify if the issue was related to my ISP, but the problem persisted. I also cleared the app data, but the search bar still didn’t work.

I hope this issue can be resolved soon. Overall, the app is fantastic, especially for fans of the Pixel UI. Great work on this project!

### Steps to reproduce

1. Open the Weather Master App
2. Click on the top bar says, "Current Location"
3. Click on the plus icon at the bottom.
4. Type any location name.

### What was the expected result?

The search bar should allow users to input a location manually and display accurate weather information for the entered location. This feature should work independently of GPS settings.

### What provider are you using?

Open-metro

### Put here any screenshots or videos (optional)

![Screenshot_2024-11-26-07-43-30-389_com example weathermaster](https://github.com/user-attachments/assets/50877198-5d70-40ba-ac41-d1f849017c01)

**Comment by PranshulGG** [comment]
@itz-rj-here it works fine please click the search button 

![Screenshot_20241126-073412.png](https://github.com/user-attachments/assets/f5ee1a51-b19b-4404-bb32-56624dd810a6)

**Comment by itz-rj-here** [comment]
Ohh, I forgot to tell my Device Information. 

Device Name: Redmi Note 12 Pro 5g
Variant: Global
Android Version: 14

**Comment by itz-rj-here** [comment]
> @itz-rj-here it works fine please click the search button 
> 
> ![Screenshot_20241126-073412.png](https://github.com/user-attachments/assets/f5ee1a51-b19b-4404-bb32-56624dd810a6)
> 
> 

Well but I still don't see any location as i type on the search bar. As i also showed the screenshot.

**Comment by itz-rj-here** [comment]
Ohh. I am really sorry. I forgot to click on the search button on the keyboard. Silly me. :(
Anyways sorry for my mistake.
