### ISSUE TITLE
Wrong country alerts for Chile

### ISSUE THREAD

**Issue by Anihilitus** [PranshulGG/WeatherMaster#161]
The app shows the alerts of China for any Chile locations, does not matter what provider is selected. 

![Screenshot_2024-11-26-14-05-30-449_com example weathermaster](https://github.com/user-attachments/assets/ad203f68-dfb8-40d6-a330-56748ab79cea)
![Screenshot_2024-11-26-14-05-34-712_com example weathermaster](https://github.com/user-attachments/assets/29214d83-7451-4051-95b9-7b6ab40353fb)

**Comment by PranshulGG** [comment]
Yep, it’s an issue with the API that provides alerts. This will be fixed in the next version.
