### ISSUE TITLE
App Freezes at startup

### ISSUE THREAD

**Issue by zakaboo** [PranshulGG/WeatherMaster#162]
### Describe your issue

When I open the app it has a blank page with current location and the settings cog at the top.  I also have the progression band moving across the screen. But it never progresses and actually loads.  I've tried different providers but get the same result.
OS is Calyxos,  Android 15 on Pixel 8 Pro

### Steps to reproduce

Open the app

### What was the expected result?

App to load correctly

### What provider are you using?

Open-Meteo (Global)

**Comment by PranshulGG** [comment]
@zakaboo did you deny the location permission?

**Comment by zakaboo** [comment]
Permissions for location is set to "Allow only while using the app"

**Comment by PranshulGG** [comment]
Please check your system location service or manually add your location.

**Comment by zakaboo** [comment]
Hi,  I've manually added my location and it is now working for my current location.  Is there a way I can set to update as per current location?  When I installed I didn't get the option to set permission to "Allow all the time" as I did when I  set up Breezy weather.  Is that the issue? I would prefer to use your app as it has my local weather source.

**Comment by PranshulGG** [comment]
> Hi, I've manually added my location and it is now working for my current location. Is there a way I can set to update as per current location? When I installed I didn't get the option to set permission to "Allow all the time" as I did when I set up Breezy weather. Is that the issue? I would prefer to use your app as it has my local weather source.

Have you checked if location services are enabled on your device? The app relies on them to automatically detect your location each time you open it. If location services are turned off, the app won’t be able to access your location.



![Screenshot 2024-11-28 134312](https://github.com/user-attachments/assets/6ad2900d-9839-4ad1-899b-6001309700a7)

**Comment by zakaboo** [comment]
Yes Location services is selected.

**Comment by PranshulGG** [comment]
Maybe try again with the latest version

**Comment by zakaboo** [comment]
Thanks PranshulGG I've down loaded version 1.88W and it seems to be working fine now.  It's a great app thankyou.

**Comment by PranshulGG** [comment]
No worries, if you got anything else let me know.
