### ISSUE TITLE
Improve widgets 

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#164]
These are the reasons:
1. The font is ugly
2. Doesn't have Material You colour like the one of Google Pixel.

![Screenshot_2024-11-28-20-06-48-316_ginlemon.flowerfree-edit.jpg](https://github.com/user-attachments/assets/8595d866-2bff-4c78-924a-1efd83ca7538)

_Originally posted by @Tuan1-2-3 in https://github.com/PranshulGG/WeatherMaster/issues/15#issuecomment-2506104258_

**Comment by Debjit-007** [comment]
Yes please upgrade the icons bit ia m not facing this ugly font tbh but i would like if you add the new icon used by Google its form android 12 
And in android 13 or 14 they updated that

**Comment by Debjit-007** [comment]
![Screenshot_20241129-073152](https://github.com/user-attachments/assets/60b7e6a4-2988-4d90-b8a9-51fb75110c73)
And please add these as well🤧🙏🏻🙏🏻🙏🏻

**Comment by Tuan1-2-3** [comment]
Yes, please🙂🥰

**Comment by PranshulGG** [comment]
@Tuan1-2-3 I've tested it on multiple devices, and the font works fine. It might be an issue specific to your device.

**Comment by PranshulGG** [comment]
@Debjit-007 More variants will be available soon, as the widgets area is still a work in progress.

**Comment by Tuan1-2-3** [comment]
OK. But you should change the colour. At the very least it mustn't have that gray colour.

**Comment by PranshulGG** [comment]
> OK. But you should change the colour. At the very least it mustn't have that gray colour.


This was fixed in 1.8.8.3

**Comment by Tuan1-2-3** [comment]
Sorry, I misunderstood. It works well with my main MIUI launcher.
(I am using Smart launcher 6)

![Uploading Screenshot_2024-11-29-11-23-59-227_com.miui.home-edit.jpg …]()
