### ISSUE TITLE
Widget doesn't launch the app

### ISSUE THREAD

**Issue by Generator** [PranshulGG/WeatherMaster#168]
### Describe your issue

When taping on the widget returns to (launcher) home screen instead of launching the app.

This only happens after some time after installing/updating the app.

Is the app is update the widget launches the app.

### Steps to reproduce

1. Create a widget
2. Tap on widget

### What was the expected result?

Always launch the app when tapping on widget 

### What provider are you using?

open-meteo 

### Put here any screenshots or videos (optional)

ADB log when tap on widget:
```
1732887861.919 10350   577   577 D RVH     : cache found, view=c1b44d8 entry=Weather Master cacheId=app://com.example.weathermaster/com.example.weathermaster.MainActivity1
```

**Comment by PranshulGG** [comment]
Which widget are you experiencing this issue with?
