### ISSUE TITLE
Not able to resize the widgets

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#169]
### Describe your issue

The widget is a bit too large for my needs, and I would love to resize it to a smaller size. Unfortunately, I'm having trouble doing that. Any tips would be appreciated!

### Steps to reproduce

1. Insert a widget on the home screen
2. See the issue: Can't resize

**Comment by PranshulGG** [comment]
@Tuan1-2-3 Which widget are you trying to resize? They don’t support it yet, but I’ll work on it soon

**Comment by Tuan1-2-3** [comment]
Sorry, I was số busy those days ago. They are the "Current pill", "Current round" and the "Current square" widget.
