### ISSUE TITLE
Text forcast doesn't recognize changing from C to F

### ISSUE THREAD

**Issue by ElizabethLeeCo** [PranshulGG/WeatherMaster#172]
### Describe your issue

The text forcast describing the day's weather is describing it as if it's 44°C instead of 44°F even though I have all the settings switched to imperial units. 
![Screenshot_20241130-003306](https://github.com/user-attachments/assets/70b0c30d-692a-490d-9ce5-65938663c0cd)

### Steps to reproduce

Opening the drop down of the Start Your Day text beneath the current temperature. 
![Screenshot_20241130-003737](https://github.com/user-attachments/assets/94157f33-937e-4bff-9df9-49a2bdb3b2ab)

### What was the expected result?

I expected it to say it's cold and not that it's going to be very hot. 

### What provider are you using?

Droidify

**Comment by PranshulGG** [comment]
@ElizabethLeeCo Oh wow, I hadn’t noticed that! The report is based on numbers rather than whether it’s in °F or °C. This will be fixed in the next update.

**Comment by ElizabethLeeCo** [comment]
It made me laugh when I saw it. I wish it was warmer here but maybe not *that* warm 😅
Thanks!

**Comment by PranshulGG** [comment]
fixed in 1.9.1!
