### ISSUE TITLE
wrong format of current location's temperature

### ISSUE THREAD

**Issue by friendly-user-t** [PranshulGG/WeatherMaster#177]
### Describe your issue

In the locations overview, there is a display bug in the current locations temperature. 

### Steps to reproduce

1. Click on locations
2. See temperature of current location
3. Find a leading 0 where there shouldn't be one.

### What was the expected result?

The format should be the same as displayed in saved locations 

### Which weather source are you using?

open-meteo

### Put here any screenshots or videos (optional)

![Screenshot_20241130-144929](https://github.com/user-attachments/assets/a7771218-a7fb-4d46-b9ae-a997b5945f7c)

**Comment by PranshulGG** [comment]
fixed in 1.9.1
