### ISSUE TITLE
Use System Font

### ISSUE THREAD

**Issue by pdimu** [PranshulGG/WeatherMaster#18]
Add a switch to use the system fonts
I personally don't like the custom fonts used

**Comment by pdimu** [comment]
Or even adding the feature to use another font from Google Fonts would be great

**Comment by PranshulGG** [comment]
Sure, I'll add the option to switch to the system font

**Comment by Cris-Edmundson** [comment]
I see this feature now has a setting, but when I enable it, it doesn't switch to my system font, it looks like it just switches to roboto

**Comment by Joe-D01** [comment]
> > I see this feature now has a setting, but when I enable it, it doesn't switch to my system font, it looks like it just switches to roboto
> 
> I agree,, it doesn't follow the system font
> any update to fix this, dev?

If you have a custom font installed, this feature won’t be very useful because the app can’t use custom fonts or fetch them. 99% of the time, it defaults to Arial, which is also the system font on most devices (along with Roboto). Plus, some fonts just don’t look good with the app’s UI.

**Comment by PranshulGG** [comment]
Like @Joe-D01 said, this was the main reason it was removed, because it always defaulted to Arial, and Roboto is a much better choice.
