### ISSUE TITLE
DWD not sticking as provider

### ISSUE THREAD

**Issue by thilakm-git** [PranshulGG/WeatherMaster#184]
### Describe your issue

When picking DWD as the main provider in settings, it never sticks after hitting the save button. It always falls back to open meteo.

Running latest version on 

### Steps to reproduce

Go to settings; pick DWD as main provider and hit save; open meteo is shown as main provider in main settings page

### Which weather source are you using?

DWD

**Comment by PranshulGG** [comment]
@thilakm-git I just checked, and yeah, there’s a typo in the DWD value, which causes the error and makes it switch back to Open-Meteo. This will be fixed in the next version.
