### ISSUE TITLE
Still pulling alert information from wrong country 

### ISSUE THREAD

**Issue by Anihilitus** [PranshulGG/WeatherMaster#186]
Location is set to Santiago de Chile, yet it shows alerts for China. Made an issue about it before that had supposedly been fixed but it is still happening

![Screenshot_2024-12-02-23-57-09-520_com example weathermaster](https://github.com/user-attachments/assets/7549a6dd-bad7-4c86-9567-6ec85fc52865)

**Comment by PranshulGG** [comment]
@Anihilitus This issue is likely going to take some time to fix since it’s caused by the API, not my code.

**Comment by Anihilitus** [comment]
Any chance of adding an option to disable weather alerts, or change the alerts provider?

**Comment by PranshulGG** [comment]
> @PranshulGG Any chance of adding an option to disable weather alerts, or change the alerts provider? 

There isn’t a newer API option right now, but if I can’t fix it, I’ll consider adding a toggle to turn it on or off.
