### ISSUE TITLE
Allow disabling the temperature text effect

### ISSUE THREAD

**Issue by SehrGuterCode** [PranshulGG/WeatherMaster#187]
### Problem Statement

Currently, after opening the app the temperature counts up slowly until it reaches the correct number. If I just want to take a quick look at the temperature and don't have much time, it's annoying to have to wait for the effect to complete.

### Proposed Solution

Add a setting for disabling this effect.

**Comment by PranshulGG** [comment]
@SehrGuterCode The branch isn’t updated yet, but the code will be in the settings file if you want to check it out once 1.9.3 is released.
