### ISSUE TITLE
Widget doesn't updates and doesn't open the app

### ISSUE THREAD

**Issue by goulartin** [PranshulGG/WeatherMaster#189]
### Describe your issue

While using the "Current pill" widget, the weather information displayed on it doesn't seem to update automatically, having to open the app to force update it. 
When I try to tap the same widget, it won't deliver any response.

I noticed this only happens after some time after placing the widget on the launcher (OneUI, Nova, hyperion and Lawnchair tested).

### Steps to reproduce

1. Install version 1.9.1 (#168 fixed)
2. Place down any widget
3. Wait some time
4. Click on widget

### What was the expected result?

Automatic refresh and update of the widgets. And to launch the app when clicked on.

### Which weather source are you using?

Open-meteo

**Comment by PranshulGG** [comment]
duplicate #181
