### ISSUE TITLE
Suggestion feature

### ISSUE THREAD

**Issue by tamarindojuice** [PranshulGG/WeatherMaster#2]
Since it's (very well) made to mimick the pixel weather app, a welcome addition is support for M3 themed icon.
Even further, support for a pill like weather widget (as avaliable on pixel devices).

**Comment by PranshulGG** [comment]
> Since it's (very well) made to mimick the pixel weather app, a welcome addition is support for M3 themed icon.
> Even further, support for a pill like weather widget (as avaliable on pixel devices). 



Hey! I'm currently working on the widgets. Could you please clarify what you mean by M3-themed icons? Are you referring to the weather icons by any chance? 😅

**Comment by tamarindojuice** [comment]
Sorry for not being clear. I mean themed icon (app itself) on launcher, that changes its color according to wallpaper set. If i can recall it right, it will need an monochromatic icon and some aditional lines 

Like this:
![Screenshot_20240822_071412](https://github.com/user-attachments/assets/bd6ab17c-bf8d-4e62-907c-5f3dd15ec7aa)

Some aditional info here:
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive?hl=en

**Comment by PranshulGG** [comment]
Thank you for the clarification. I will update the app with a monochromatic
icon in the next version.

Best regards,
Pranshul

**Comment by tamarindojuice** [comment]
Themed icon added in last build, working well here, thank you for your support!
When ready for translation count on me to translate it to pt_BR.  ;)
My best regards.

**Comment by PranshulGG** [comment]
Haha, thanks!
