### ISSUE TITLE
Gadgetbridge Support

### ISSUE THREAD

**Issue by stoniwankenobii** [PranshulGG/WeatherMaster#20]
Would be great for sending this data to Pebbles and even Smartspacer to replace googles at a glance. Maybe this will [help?](https://gadgetbridge.org/internals/development/weather-support/)

**Comment by PranshulGG** [comment]
> Would be great for sending this data to Pebbles and even Smartspacer to replace googles at a glance. Maybe this will [help?](https://gadgetbridge.org/internals/development/weather-support/)

I'm not very familiar with Pebbles and Smartspacer, but I'll try to see if I can make it work

**Comment by HomemadeAdvanced** [comment]
Is it possible to add general gadgetbridge support like these apps: https://gadgetbridge.org/basics/integrations/weather/ ?

Thanks in advance.

**Comment by dev0T** [comment]
Just wanted to show support for this. I recently purchased a smart watch and it would be great if it could get the data from Weather Master, avoiding the need of another app.
