### ISSUE TITLE
Expose Open-Meteo models

### ISSUE THREAD

**Issue by 0-5-0** [PranshulGG/WeatherMaster#203]
### Problem Statement

Sometimes the Open-Meteo "Best Match" model isn't always the best match for my region.

### Proposed Solution

Open-Meteo models could be exposed so that users can select the Open-Meteo model that works best for them.

See OSS Weather (preferences -> providers -> preferred model) and Breezy Weather (under Location preferences -> Weather Models, when you edit a location) as examples.

**Comment by PranshulGG** [comment]
OK!
