### ISSUE TITLE
Bugs of Vietnamese language

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#207]
### Wrong words & sentences:
![IMG_20241206_193415](https://github.com/user-attachments/assets/8c863c48-b7c0-4306-ba1a-aed376983332)
![IMG_20241206_193526](https://github.com/user-attachments/assets/28f224a1-75ab-4781-95bd-90635316186c)

### And the font is not good:
![Screenshot_2024-12-06-19-18-59-817_com example weathermaster](https://github.com/user-attachments/assets/0d8d72bb-0670-4338-8705-28735d97baea)

### Steps to reproduce

1. The app uses the wrong words and sentences.
2. The font is ugly.

### What was the expected result?

I suggest you add some fonts that support Vietnamese like Roboto, Montserrat, Open Sans, Inter, ...
[Google Font](https://fonts.google.com/?lang=vi_Latn)

### Which weather source are you using?

Met Norway

**Comment by PranshulGG** [comment]
Right now, the app uses Outfit font and Product Sans. I think I should switch to Product Sans, as that should work fine.

**Comment by Tuan1-2-3** [comment]
I got some more bugs:
![IMG_20241207_131211.jpg](https://github.com/user-attachments/assets/00114eb9-9103-48da-b5fc-2b1e81fc591a)

![IMG_20241207_131026.jpg](https://github.com/user-attachments/assets/55590f47-6384-43fa-855e-eb072e2554b7)
