### ISSUE TITLE
Widget resize issue

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#208]
### Describe your issue

I have met a bug when resizing some widgets.

### Steps to reproduce

1. Insert one of these widgets: Current and hourly, Current round, Current square, Square.
2. Resize it and see the issue

### Which weather source are you using?

Met Norway

### Put here any screenshots or videos (optional)

![Screenshot_2024-12-06-20-05-34-301_com miui home](https://github.com/user-attachments/assets/3862b271-78c1-48e4-a3fd-e39a876e3e27)

**Comment by PranshulGG** [comment]
Well, this is kind of intentional. If you over-resize, of course, it will look worse. I did this because I couldn’t get the resizing issue to work. Maybe if I find a solution for this... but you don’t have to over-resize it anyway

**Comment by Tuan1-2-3** [comment]
I only need smaller a bit but I can't resize it to a smaller size because it will make the widget look bad. (This image show the smallest size that it can be)

**Comment by PranshulGG** [comment]
> I only need smaller a bit but I can't resize it to a smaller size because it will make the widget look bad. (This image show the smallest size that it can be)

OK, maybe i'll have to rework on the widgets then

**Comment by Tuan1-2-3** [comment]
Some widgets of some apps (:⁠-⁠| ), when enlarging, will increase the size; when making it small,l, they will remove some free space and will have a smaller size, not cutting the widgets.
