### ISSUE TITLE
Feature Request, App Open Speed

### ISSUE THREAD

**Issue by IndomitableAlbus** [PranshulGG/WeatherMaster#209]
Please can I submit a 'Feature Request' well more of just a request.

App start speed ....

I appreciate there's a lot to load on App start but the speeds a little sluggish.

Can you find a way to cut the loading time down please, maybe add a toggle option to keep the App running in the background, whatever it takes really.

**Comment by PranshulGG** [comment]
@IndomitableAlbus There's not much I can do about the loading time, as it depends on how fast the API returns the data and your internet speed.

Background updates won’t make much difference if the data is old, as the app checks the time when the data was last cached and fetches the latest data accordingly. But I’ll see what I can improve.

**Comment by IndomitableAlbus** [comment]
Thank you for taking the time to explain things, any speed increase, no matter how small would help, so I'm pleased to hear you'll see what you can do.

**Comment by PranshulGG** [comment]
@IndomitableAlbus One more thing—if you're using your device's location, it might be slower because the app has to fetch your current location every time. If you save your location and set it as your default, the app will load faster since it won't need to fetch the location repeatedly.
