### ISSUE TITLE
Weather Radar Doesn't Show Future Radar

### ISSUE THREAD

**Issue by HonestAbe7** [PranshulGG/WeatherMaster#21]
I am not sure if this is a bug but I noticed that the radar only shows up to the current time. Is there any way to show for the future? This totally defeats why there is a radar in my opinion if you can't see the future radar. Thanks

**Comment by PranshulGG** [comment]
> I am not sure if this is a bug but I noticed that the radar only shows up to the current time. Is there any way to show for the future? This totally defeats why there is a radar in my opinion if you can't see the future radar. Thanks

I haven't found a good radar yet, so I'll have to stick with this one for now.
