### ISSUE TITLE
Current location: show the placename

### ISSUE THREAD

**Issue by fparri** [PranshulGG/WeatherMaster#216]
### Problem Statement

Would that be possible to show the name.of the current location you are seeing?

### Proposed Solution

Show the name of th location and not just "current location"

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified index.html to display the current location name and updated renderWeather.js to populate this information.

You can review changes in this commit: https://github.com/mnmnk43434/PranshulGG-WeatherMaster-216/commit/894e9c2d093903bb48a3e47657c1e8f562663bd8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Tuan1-2-3** [comment]
Mentioned in #129 .

**Comment by PranshulGG** [comment]
duplicate #129
