### ISSUE TITLE
Vietnamese language bug again😅

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#218]
## I have some good news and some bad news:
# Good news:
![Screenshot_2024-12-08-08-39-02-088_com android chrome-edit](https://github.com/user-attachments/assets/86c841aa-e644-4773-90d9-8ac5640d86b3)
# Bad news:
![Screenshot_2024-12-08-08-43-09-768_com example weathermaster-edit](https://github.com/user-attachments/assets/3abf7162-147c-42e4-9c89-f8742ccf2716)
![Screenshot_2024-12-08-08-42-35-459_com example weathermaster-edit](https://github.com/user-attachments/assets/06270d0e-fb9f-47d7-980b-1471fde27db2)
![Screenshot_2024-12-08-08-43-34-697_com example weathermaster-edit](https://github.com/user-attachments/assets/d2c44211-e42e-4de4-83f2-eb67b6d93274)
![Screenshot_2024-12-08-08-44-21-428_com example weathermaster-edit](https://github.com/user-attachments/assets/fdf43089-b1d4-4137-aae4-e81a6143c136)
![Screenshot_2024-12-08-08-41-21-595_com example weathermaster-edit](https://github.com/user-attachments/assets/7a533eb9-487f-4103-ad85-421cc677f792)
![Screenshot_2024-12-08-08-40-51-691_com example weathermaster-edit](https://github.com/user-attachments/assets/7b95e880-2568-43ad-b904-87b276afc221)
![Screenshot_2024-12-08-08-39-37-896_com example weathermaster-edit](https://github.com/user-attachments/assets/ee23f040-0bc9-48e0-8a39-8d01d3b93e43)

### Steps to reproduce

Some text in the app hasn't been translated yet.

### Which weather source are you using?

Met Norway

**Comment by PranshulGG** [comment]
Ok but these aren't bugs, those weren't translated when the version was released

**Comment by Tuan1-2-3** [comment]
OK! And you mean that it will translate in the next version, right?

**Comment by PranshulGG** [comment]
> OK! And you mean that it will translate in the next version, right?

yes
