### ISSUE TITLE
Question: Upload the 'Quick summary' sentences to Crowdin

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#222]
Hey there! Would you mind uploading the 'Quick summary' sentences to Crowdin? It would really help me out. Thanks a bunch!
![Screenshot_2024-12-08-19-55-13-854_com.example.weathermaster-edit.jpg](https://github.com/user-attachments/assets/29e1b2fb-82bc-429f-acd1-59dacbeed48d)

**Comment by PranshulGG** [comment]
@Tuan1-2-3  Currently, translations can’t be applied to the summary because the text is combined dynamically. Until I find a solution, it will remain in English.

**Comment by Joe-D01** [comment]
@Tuan1-2-3 you can translate now

**Comment by Tuan1-2-3** [comment]
OK! But on Crowdin?

**Comment by Tuan1-2-3** [comment]
I'll check that out.
