### ISSUE TITLE
APIs: Italian Meteo AM

### ISSUE THREAD

**Issue by gorlix** [PranshulGG/WeatherMaster#224]
### Name of the provider

Meteo AM: [https://www.meteoam.it/](https://www.meteoam.it/)

this providere represents the **Italian Air Force Weather**

### Reason for Request

italian air force is one of the most reliable weather providers in italy

- currently already implemented within [Breezy Weather](https://github.com/breezy-weather/breezy-weather) current implementation: [meteoAM](https://github.com/breezy-weather/breezy-weather/tree/main/app/src/src_nonfreenet/org/breezyweather/sources/meteoam)

### Key Features or Benefits

accurate throughout italy and many parts of southern europe

### Provider's API Information

yes

### Regions Supported

specific

### Specify Regions

South Europe, Italy, Frace, Spain, Swiss

**Comment by PranshulGG** [comment]
@gorlix I looked into it, and it seems this API is undocumented and missing a lot of data. Here's what it provides:

5-day daily forecast
5-day hourly forecast
Temperature
Precipitation
Wind
Humidity
Pressure
It doesn't include other details like "feels like" temperatures and more.
