### ISSUE TITLE
Add more widget

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#225]
## Can you add this widget?
This is the design:
![Screenshot_2024-12-09-06-26-37-256_com miui home-edit](https://github.com/user-attachments/assets/4db296b2-207a-4da3-99e3-d8f3a653e11b)

Source: Mi theme

## With customizable clock 
Design:
![Screenshot_2024-12-09-17-36-19-210_com pashapuma pix material you dark](https://github.com/user-attachments/assets/04331c23-b0a6-4035-ada4-1a926002afc9)
![Screenshot_2024-12-09-17-36-28-421_com pashapuma pix material you dark](https://github.com/user-attachments/assets/f7d07ebf-ec50-42c7-9b73-c56f8887c7e6)
![Screenshot_2024-12-09-17-36-32-784_com pashapuma pix material you dark](https://github.com/user-attachments/assets/3955c32b-1356-4fa4-9905-e3a12b22256f)
![Screenshot_2024-12-09-17-36-36-978_com pashapuma pix material you dark](https://github.com/user-attachments/assets/fac61f76-bdd1-4b67-886d-89156de768f2)
![Screenshot_2024-12-09-17-36-41-229_com pashapuma pix material you dark](https://github.com/user-attachments/assets/af19cf38-2589-462f-8b57-2b57c6eed9ea)
![Screenshot_2024-12-09-17-36-44-173_com pashapuma pix material you dark](https://github.com/user-attachments/assets/1e620983-43c6-4b05-b8c3-325fb6514db4)
![Screenshot_2024-12-09-17-36-47-350_com pashapuma pix material you dark](https://github.com/user-attachments/assets/12711f67-7471-4524-8ff1-1615f5cb5c19)
![Screenshot_2024-12-09-17-36-51-047_com pashapuma pix material you dark](https://github.com/user-attachments/assets/cdbfe724-770f-4413-9a3c-3488f87bb8f6)
![Screenshot_2024-12-09-17-36-53-827_com pashapuma pix material you dark](https://github.com/user-attachments/assets/acd76e0d-af2b-4ecd-b00b-149a1cf70889)
![Screenshot_2024-12-09-17-36-58-204_com pashapuma pix material you dark](https://github.com/user-attachments/assets/09c89234-7b22-4c61-9695-965bc6c14a2a)
![Screenshot_2024-12-09-17-37-03-599_com pashapuma pix material you dark](https://github.com/user-attachments/assets/cdfcd323-15c2-455b-b6f3-a1ca42f9da02)
![Screenshot_2024-12-09-17-37-07-462_com pashapuma pix material you dark](https://github.com/user-attachments/assets/ea22432f-dcfb-4ddb-aeb1-8da952b2d946)

Source: Pix material you light/dark

### Proposed Solution

Could you please add some Material You design elements to it? I’d love to see it a bit more lively instead of just plain!

**Comment by Joe-D01** [comment]
Why do you need clock widgets in a weather app?

**Comment by Tuan1-2-3** [comment]
Yeah, because the normal pill widget is too large make it next to the clock widget of pix Material You light/dark.

**Comment by Tuan1-2-3** [comment]
It looks weird!

**Comment by Joe-D01** [comment]
Clocks aren’t planned for now, but widgets will improve with future updates. This feature has already been requested in #213 or #210. @PranshulGG, could you close this?

**Comment by Tuan1-2-3** [comment]
Sorry for bothering you.

**Comment by taseencr** [comment]
@Joe-D01 including a clock feature in a weather app widget has actually become a common practice nowadays. Displaying both time and weather in a single widget enhances convenience, keeping the home screen minimized and clutter-free. Tbh it's the only feature that I miss from other weather apps, it would be really nice if you could find the time to add it! :D

![Screenshot_2024-12-18-01-49-15-546_com miui home-edit](https://github.com/user-attachments/assets/1b020e0a-7c9c-4c20-a6d5-db5d64b777ad)
