### ISSUE TITLE
About commit eedd1fd52fd0f9589fce8749eed24a0c70584d7d

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#229]
### Problem Statement

I see that your eedd1fd52fd0f9589fce8749eed24a0c70584d7d commit about Vietnamese change the word 'Settings' from 'Cài đặt' to 'Thiết đặt'. But many devices use the word 'Cài đặt' for their settings app.

### Proposed Solution

Why do you change 'Cài đặt' to 'Thiết đặt'?

### Additional Context

![Screenshot_2024-12-11-11-48-43-810_com miui home-edit](https://github.com/user-attachments/assets/8deb9697-e384-4e16-9107-3b12ca717504)

Source: My device

**Comment by PranshulGG** [comment]
@Tuan1-2-3 I did not change it; maybe someone else did.

**Comment by Tuan1-2-3** [comment]
I don't know. I will take a screenshot for you.

**Comment by Tuan1-2-3** [comment]
![Screenshot_2024-12-11-12-01-13-116_com.github.android.jpg](https://github.com/user-attachments/assets/4c756d6b-3078-4422-9318-a952318aba9c)

**Comment by PranshulGG** [comment]
> I don't know. I will take a screenshot for you.

You can change it, if you think its wrong.

**Comment by Tuan1-2-3** [comment]
OK! I will.
