### ISSUE TITLE
Add open-meteo as a source

### ISSUE THREAD

**Issue by PinguDEV-original** [PranshulGG/WeatherMaster#23]
Hey! I really appreciate this app, but I think it would be cool to have open-meteo implemented as a dats source.

**Comment by PranshulGG** [comment]
> Hey! I really appreciate this app, but I think it would be cool to have open-meteo implemented as a dats source.

I'm working on adding Open-Meteo for the next version of the app, so it will be available soon

**Comment by pdimu** [comment]
@PranshulGG this is done, mind closing it?
