### ISSUE TITLE
Contributor's Guide

### ISSUE THREAD

**Issue by p134c0d3** [PranshulGG/WeatherMaster#231]
Hello!

Really enjoying the app, and would like to help contribute if possible, though this would be my first mobile application contribution.

Would it be possible to create a contribution guide for people that would like to help contribute to issues?

If that isn't possible, would you be alright with me reaching directly out to you to get started on contributing?

**Comment by PranshulGG** [comment]
@p134c0d3 Instead of creating a full contribution guide, I think it would be more effective if you reached out to me directly. Contributing to the app isn’t too complicated, and I’d be happy to guide you through the process to get started.

**Comment by PranshulGG** [comment]
Or you can also join the discord server!

**Comment by p134c0d3** [comment]
@PranshulGG I'd love to join the discord. What's the invite link for that?

**Comment by Joe-D01** [comment]
> @PranshulGG I'd love to join the discord. What's the invite link for that?

@p134c0d3 dude, you can check the app  settings or the README
