### ISSUE TITLE
Visibility usws wrong temperature unit

### ISSUE THREAD

**Issue by LordOfTheSheps** [PranshulGG/WeatherMaster#233]
### Describe your issue

When the units are set to freedom units, the Visibility tile shows in miles as expected, but when cliking on it it displays in kilometers. 

### Steps to reproduce

1. Change visibility settings to miles
2. Go to home page
3. Click the visibility tile

### What was the expected result?

To show units in miles

### Which weather source are you using?

Open-metro

### Put here any screenshots or videos (optional)

![Screenshot_20241212-082441](https://github.com/user-attachments/assets/09183b8a-4a90-4982-bc0b-a4a6f7197fe9)
![Screenshot_20241212-082437](https://github.com/user-attachments/assets/32ebfb77-0a61-46d7-bffb-293177a396a2)

**Comment by PranshulGG** [comment]
I don't know how this wasn't noticed, lol.
