### ISSUE TITLE
Wrong date on detailed Daily Forecast 

### ISSUE THREAD

**Issue by Anihilitus** [PranshulGG/WeatherMaster#234]
So today is Thursday, homescreen of the app shows everything correctly, however when going into the detailed view of the daily forecast, it thinks it's Friday (wrong date), and all other subsequent dates are wrong too. 

https://github.com/user-attachments/assets/12b7d86f-c00c-45f5-9463-f448e624de99

**Comment by PranshulGG** [comment]
@Anihilitus For some reason, the video isn't working and won't let me play it. This might happen if the data is outdated and hasn't been refreshed. If the data is new, I would like to know which weather provider you're using.

**Comment by Anihilitus** [comment]
Weird. Currently using open meteo! I'm sending some screenshots of the issue 

![Screenshot_2024-12-12-22-44-53-222_com example weathermaster](https://github.com/user-attachments/assets/99485f37-efb5-400b-bfbb-9e78d5b4f56f)
![Screenshot_2024-12-12-22-44-59-792_com example weathermaster](https://github.com/user-attachments/assets/960a3a3d-0a20-44ad-9255-aa27fa6d9c0d)
![Screenshot_2024-12-12-22-45-04-512_com example weathermaster](https://github.com/user-attachments/assets/058ce71b-815f-4912-bf34-6f69b4d5a1a7)

**Comment by Tuan1-2-3** [comment]
Why my app doesn't have that issue?
![IMG_20241213_173707.jpg](https://github.com/user-attachments/assets/1a1c31e0-e351-4cee-9cf7-17075ca92e34)

![IMG_20241213_173650.jpg](https://github.com/user-attachments/assets/cb718e08-af60-4649-aa18-95379a50e838)

![IMG_20241213_173627.jpg](https://github.com/user-attachments/assets/60773975-cc73-4837-8eaf-d2bc014d9480)

![IMG_20241213_173725.jpg](https://github.com/user-attachments/assets/6d4c3837-02a3-4943-95ad-8e4485d780fe)

**Comment by Tuan1-2-3** [comment]
I'm using Met Norway. Did Open-Meteo cause the issue?
