### ISSUE TITLE
Import the Italian translation from Poeditor.com

### ISSUE THREAD

**Issue by mapi68** [PranshulGG/WeatherMaster#238]
### Problem Statement

I have completed a lot of time ago the italian translation of WM but it isn't merged into master.

### Proposed Solution

Import from poeditor.com or import directly the [json file](https://github.com/user-attachments/files/18142834/WeatherMaster_Italian.json).

### Alternatives Considered

Now I have seen that you moved all translations in crowdin!

**Comment by Joe-D01** [comment]
This will not be possible, as all the strings are different and do not match the ones on POEditor. If I did that, I would have to redo all the languages, which is not feasible, especially since the translations on POEditor are incomplete.

**Comment by PranshulGG** [comment]
This will not be possible, as all the strings are different and do not match the ones on POEditor. If I did that, I would have to redo all the languages, which is not feasible, especially since the translations on POEditor are incomplete.

**Comment by Joe-D01** [comment]
I don't get why you need POEditor translations. Crowdin is complete; you can translate there.
