### ISSUE TITLE
Radar Widget? 

### ISSUE THREAD

**Issue by ElizabethLeeCo** [PranshulGG/WeatherMaster#248]
### Problem Statement

I would love to not have to use The Weather Channel for a decent radar widget. 

### Proposed Solution

Basically anything resizable with zoom capabilities would be awesome. The other radar widgets I've tried are zoomed out so far that it's impossible to see local rain/snow on it. 

### Acknowledgements

- [X] I have searched the existing issues and discussions to ensure this feature has not already been requested.
- [X] I understand that submitting a request does not guarantee it will be implemented.
- [X] I have provided all necessary information to clearly explain my request.

**Comment by Joe-D01** [comment]
@ElizabethLeeCo This might be easy to implement and could be included in the next release, but just a heads-up: you'll need to refresh the widget using the refresh button on the widget itself, as background updates are still an issue.

**Comment by PranshulGG** [comment]
There are some challenges that make it hard to pull off in a widget format.

Radar data usually has a fixed resolution and coverage area, so even though you can zoom in within an app, the level of detail is still limited. Widgets, on the other hand, are meant to be lightweight and easy to glance at, so they don’t usually support interactive features like zooming.

Plus, adding zoom and real-time updates would drain a lot of battery and resources, which isn’t great for a widget.

Maybe check out [Windy](https://play.google.com/store/apps/details?id=com.windyty.android) – they have some great radar widgets

**Comment by ElizabethLeeCo** [comment]
Ah, ok. That's probably why the ones I liked were either abandoned or dropped from apps. I live in Tornado Alley so we are very ser
