### ISSUE TITLE
Make the direction rotate

### ISSUE THREAD

**Issue by PinguDEV-original** [PranshulGG/WeatherMaster#25]
It would be soo cool to have this direction wind thingy rotate to the compass.
![IMG_20240906_084819](https://github.com/user-attachments/assets/8cab8d2b-5b96-46cf-9be6-db80665f3894)

**Comment by PranshulGG** [comment]
So it rotates in the direction of your phone, like a compass? Hmm, yeah, I was thinking about adding that before. I'll see if I can make it work.

**Comment by gaabster** [comment]
I think that right now, the arrow rotates in the wrong (opposite) direction. Wind directions in weather forecast indicate which direction the wind is coming from rather than where it is blowing to. Please correct me if I'm wrong.

**Comment by PranshulGG** [comment]
Yep, it shows where the wind is coming from instead of where it's blowing to. Open-Meteo and other APIs only provide the direction the wind is coming from, not where it's blowing to.

**Comment by gaabster** [comment]
Hmm I think I worded my statement incorrectly, I apologise for that.

Look at the screenshot below:
<details>
  <summary>Details</summary>

![Screenshot_20240921-092231_WeatherMaster](https://github.com/user-attachments/assets/38b737ad-5219-448f-9131-a0bcd6b383bd)
</details>

The wind direction is **N**, the arrow points north, but it should in fact point south. The **N** tells us where the wind is coming from.

**Comment by PranshulGG** [comment]
Oh, I just noticed that the arrow it's using is wrong. Thanks for pointing it out! It'll be fixed in the next version.
