### ISSUE TITLE
Improvements for Swipe Gestures  

### ISSUE THREAD

**Issue by PranshulGG** [PranshulGG/WeatherMaster#250]
- Create a dummy page for the swipe animation.  
- Disable pull-to-refresh while swiping.  
- Make gestures more responsive to the app by avoiding adding the listener to containers.  
- Add a 1-second delay before each swipe to prevent data merging.  
- Handle incomplete swipes gracefully by snapping the view back to its original state or completing the action based on intent.

**Note:** Currently, there is a 1500ms delay between swipes, so you have to wait before making a new swipe.

**Comment by Joe-D01** [comment]
Cool
