### ISSUE TITLE
More translations missing

### ISSUE THREAD

**Issue by Kesaa89** [PranshulGG/WeatherMaster#255]
![Screenshot_20241226-111940~2](https://github.com/user-attachments/assets/3d82b5bc-1d9b-434a-948f-b6a78824fd3c)
![Screenshot_20241226-112055~2](https://github.com/user-attachments/assets/267f11ee-91b2-4c0b-9b34-9ccdcbe6b400)
![Screenshot_20241226-111540~2](https://github.com/user-attachments/assets/f6a7a39a-695c-4883-b981-a216bc5037fd)
![Screenshot_20241226-111550~2](https://github.com/user-attachments/assets/3cd3d186-5604-4e62-bebd-954d520b4acf)
![Screenshot_20241226-111557~2](https://github.com/user-attachments/assets/5299af9b-0417-4977-a18c-e96478dcf671)

**Comment by PranshulGG** [comment]
@Kesaa89 These ones aren't missing; they just haven't been translated yet
