### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Kurczaczki69** [PranshulGG/WeatherMaster#259]
![Screenshot_20241228-215957.png](https://github.com/user-attachments/assets/3040dff1-26ee-4e3d-9df0-e9913d5633ef)

Translations for the month names are missing (Jan, Feb  etc.)

Also here in weather alerts it says "CurrentDeviceLocation" (I highlighted it) and I don't think thats how it's supposed to look

![Screenshot_20241228-220302~2.png](https://github.com/user-attachments/assets/e0c41f54-df35-418a-b661-cbe09793e147)

Translations for those time units are also missing (highlighted)

![Screenshot_20241228-220459.png](https://github.com/user-attachments/assets/dd4b5c3e-e47e-4ae6-abef-d90849e6cce1)

**Comment by PranshulGG** [comment]
@Kurczaczki69 Sadly, Crowdin has a 60,000-word limit, which is about to be exceeded, so the translations are currently delayed.

**Comment by Tuan1-2-3** [comment]
> @Kurczaczki69 Sadly, Crowdin has a 60,000-word limit, which is about to be exceeded, so the translations are currently delayed.

Does it because of the subscription?
