### ISSUE TITLE
Left swipe not working.

### ISSUE THREAD

**Issue by sarojpanda44** [PranshulGG/WeatherMaster#272]
### Describe your issue

After latest version 1.13.2 update, I noticed that the left swipe doesn't change the locations. Only the right swipe changes the locations

### Steps to reproduce

Save few locations. And try left swipe to change location on froggy image. Nothing happens

### What was the expected result?

The left swipe should change the locations in reverse order.

### Which weather source are you using?

Open-Meteo

### Acknowledgements

- [X] I have reviewed the existing issues to confirm that this is a unique report and not related to any currently open or closed tickets.
- [X] I understand that this app is provided as-is, without any guarantees, and I might not receive a response to my request. Sometimes you might not get the response you want.

**Comment by Tuan1-2-3** [comment]
@sarojpanda44 I don't know why. My app works well.

**Comment by PranshulGG** [comment]
Try changing the threshold because it also works fine here

**Comment by sarojpanda44** [comment]
On latest version 1.13.2?

**Comment by Tuan1-2-3** [comment]
You had to dodge the slider (I don't know what its name 😅, clarified in the image) in the quick summary.
![Screenshot_2024-12-30-19-50-43-809_com example weathermaster-edit](https://github.com/user-attachments/assets/18e198f8-980c-4cc6-8202-727ce61c7734)

**Comment by PranshulGG** [comment]
> On latest version 1.13.2?

Yes

**Comment by Tuan1-2-3** [comment]
> @Tuan1-2-3 On latest version 1.13.2?

Yes!

**Comment by sarojpanda44** [comment]
For me. It worked on slightly diagonal swipe. Perfect straight left swipe doesn't work. Perfect straight right swipe and diagonal right swipe works fine.

**Comment by Tuan1-2-3** [comment]
Weird!

**Comment by Tuan1-2-3** [comment]
I'll try again.

**Comment by PranshulGG** [comment]
> For me. It worked on slightly diagonal swipe. Perfect straight left swipe doesn't work. Perfect straight right swipe and diagonal right swipe works fine.

@sarojpanda44  I recommend using a threshold of 50, as it works better. Also, keep in mind there’s a 1-second cooldown before the next swipe.

**Comment by sarojpanda44** [comment]
Yes. Cool down is not an issue. I'm swiping slowly 😄
Just strange with left diagonal swipe.

**Comment by Tuan1-2-3** [comment]
https://github.com/user-attachments/assets/1323f1a5-b401-42e2-8126-6298f69424b3

**Comment by Tuan1-2-3** [comment]
This is when the threshold is 50

**Comment by sarojpanda44** [comment]
I'm closing this as it is working with bit diagonal up swipe
