### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by Marcopolos51** [PranshulGG/WeatherMaster#3]
hello.
 the app is in english, can i help you translate it into french?

 thanks

**Comment by MikronT** [comment]
Integration of Weblate or any other community localization platform would be a nice choice

**Comment by C-O-D** [comment]
I can only agree, wait with the further use until a German translation is available...

**Comment by frankh93** [comment]
i agree too, i can help with spanish translation

**Comment by MikronT** [comment]
I can help with Ukrainian translation

**Comment by tomz00** [comment]
I'll do Slovak translation! Personally, I would like to rely on pull requests, rather than weblate or any 3rd party stuff. Just my opinion.

**Comment by PranshulGG** [comment]
I've set up POEditor for translations, but I still need to add the strings. After that, you'll be able to contribute to the translations.

**Comment by frankh93** [comment]
just let me know when it's ready and i will do my part... tysm in adding translations!

**Comment by Stzyxh** [comment]
> just let me know when it's ready and i will do my part... tysm in adding translations!

You can now translate

**Comment by frankh93** [comment]
Already done the spanish translation, but in some texts I was getting this message:
• New lines don't match (source: 1, target: 0).
• Trailing new lines don't match (source: 1, target: 0).

If there's something wrong let me know pls

**Comment by PranshulGG** [comment]
> Already done the spanish translation, but in some texts I was getting this message:
> • New lines don't match (source: 1, target: 0).
> • Trailing new lines don't match (source: 1, target: 0).
> 
> If there's something wrong let me know pls

I exported the translation to the project, and everything looks fine without any errors. If anything comes up, I'll let you know.

**Comment by tomz00** [comment]
I added Slovak translation.
