### ISSUE TITLE
Float numbers break UI

### ISSUE THREAD

**Issue by Illumes** [PranshulGG/WeatherMaster#30]
These numbers mess up these portions of the UI.
![markup_1000000389](https://github.com/user-attachments/assets/c13b4671-aa6d-4466-b354-4595c5d7e1e5)
![markup_1000000390](https://github.com/user-attachments/assets/142a5768-ac90-4ae8-ad98-15b4d2f5c01d)

**Comment by PranshulGG** [comment]
I never encountered this issue during testing. I'll round the numbers in the next version.
