### ISSUE TITLE
Incorrect high and low temperature 

### ISSUE THREAD

**Issue by linquint** [PranshulGG/WeatherMaster#31]
![Screenshot_20240911_115643_com.example.weathermaster.png](https://github.com/user-attachments/assets/1d0111c8-b1a7-4831-b85f-4af7dbafe8f0)

![Screenshot_20240911_120011_com.example.weathermaster.png](https://github.com/user-attachments/assets/63ac9f1e-95e1-4eed-aee2-502c099885e3)

**Comment by linquint** [comment]
Sorry, I should have explained the issue better. I meant this:
![Screenshot_20240911_120011_com.example.weathermaster~2.png](https://github.com/user-attachments/assets/6bc64be6-995f-469f-91cc-6745c1c3bf85)

**Comment by PranshulGG** [comment]
How is it incorrect? What's the exact issue, if I may ask?

**Comment by linquint** [comment]
It shows at the top card that the high will be 34, when looking at the 14 days forecast it says 20

**Comment by PranshulGG** [comment]
> It shows at the top card that the high will be 34, when looking at the 14 days forecast it says 20

It says 20 in the forecast because that's the average high and low for today. The top card shows the current temperature, which updates every 15 minutes, so it's not for the entire day—it's just the current condition.

**Comment by PranshulGG** [comment]
which is like 2m above the ground level

**Comment by PranshulGG** [comment]
It's not wrong; it's just showing the high and low for the current time. I hope that makes sense!

**Comment by FastCar3000** [comment]
I would like to disagree. This issue persists across different locations. No matter what location I enter, it shows a high of 34 and a low of 23 (just like what the OP said). Please reconsider.
![Screenshot_20240911-051744_WeatherMaster](https://github.com/user-attachments/assets/f5ca57de-afbc-496b-9fed-685fdda717ca)

**Comment by PranshulGG** [comment]
So you mean it shows the same values for every location? I just checked, and it's true—my bad, I misunderstood earlier. 😓

**Comment by FastCar3000** [comment]
Lol yes, it's the same for every location. And don't feel bad, the app is beautiful. Keep doing your thing. 🙏🏾
