### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by p134c0d3** [PranshulGG/WeatherMaster#33]
Hello, this looks pretty good, excited for what it could be. Just have a few bugs to mention. Located in the US, so all measurements are reflective of that. 

![Screenshot_20240913-092346_WeatherMaster.jpg](https://github.com/user-attachments/assets/5f252b5e-b096-49da-ba85-6177bf8631d5)

When expanding the moon cycle, nothing additional is shown when expanding the widget.

![Screenshot_20240913-092435_WeatherMaster.jpg](https://github.com/user-attachments/assets/24db89c8-97cb-4343-8249-604a8f15c279)

For precipitation totals, could you consider rounding to the hundredths place to reduce length (e.g. 0.01 instead of 0.01123456)?

![Screenshot_20240913-092515_WeatherMaster.jpg](https://github.com/user-attachments/assets/4dfb07c0-5659-48a7-b844-8460e257f5b7)

You may want to double check the wind speeds. I checked the wind for today and it's definitely not 34mph, and tomorrow is showing 53mph winds. 53mph winds would be a terrible storm level, and tomorrow does not show any storms and I know it won't be winds that high. 

Love the look and feel, just a few things I noticed off the bat. Thanks!

**Comment by PranshulGG** [comment]
Yeah, I know there are some issues when switching from Metric to Imperial. I didn't notice it during testing, but it's already fixed and will be included in the next update.

**Comment by PranshulGG** [comment]
As for the wind speed, it shows the maximum wind speed for the day, measured 10 meters (about 33 feet) above the ground.

**Comment by p134c0d3** [comment]
Okay, anything else I can find I'll open a new bug for them. I appreciate it! 

Are you wanting contributors, or more a solo project? If so, do you have guidelines for contributors?

**Comment by PranshulGG** [comment]
At the moment, I don't have specific guidelines for contributors, but I'll let you know if I need any for this project in the future.
