### ISSUE TITLE
Notification settings dropping error

### ISSUE THREAD

**Issue by pdimu** [PranshulGG/WeatherMaster#34]
Hi! I'm glad you finally added the notification option, but it doesn't work. When turning it on it shows a little android popup that it doesn't have something and doesn't show the notification.
Screenshot: 
![Screenshot_2024-09-13-22-00-23-056-edit_com.example.weathermaster.jpg](https://github.com/user-attachments/assets/ca6ad968-08f9-4d8d-9d38-7234e27f21c0)

**Comment by pdimu** [comment]
Duplicate in #16

**Comment by PranshulGG** [comment]
Yeah, it was working fine in the debug version, but it's having issues in the release version. This will be fixed in the next update. The android keeps destroying the activity
