### ISSUE TITLE
14 Day Forecast Shows Incorrect Day of Week

### ISSUE THREAD

**Issue by p134c0d3** [PranshulGG/WeatherMaster#36]
Hello again, I'm on the latest version, updated today. 

On the homepage, the 14 day forecast is showing today to be Friday, but it is Saturday here in the US Central Time.

Here is the 14 day forecast:
![Screenshot_20240914-122159_WeatherMaster.jpg](https://github.com/user-attachments/assets/da874d38-70d1-4ea2-a44c-a83e3f3b906e)

Here's my calendar showing today as Saturday the 14th:
![Screenshot_20240914-122826_Proton Calendar.jpg](https://github.com/user-attachments/assets/34031f45-ee40-48f2-9a33-f1debdfe8e16)

**Comment by PranshulGG** [comment]
Is it correct on the forecast page or not?

**Comment by Illumes** [comment]
I've also noticed this. In the 14 day forecast it shows "Today" and then the day after "today" on the 14 day forecast list is the day you are currently on so today is redundant. Unless it is a bug and it is mixing up the days wrong.

**Comment by PranshulGG** [comment]
I tried to find the bug, but it's showing the correct dates for every location when I search. If you could provide a screenshot, that would be helpful since I can't find it myself—or maybe it's related to your timezone?

**Comment by Illumes** [comment]
The screenshot he provided is basically what it is but I don't think it is being described enough. On the screenshot he has it says "today" and the next one is "Saturday." But it is already Saturday according to those photos. When opening the 14d forecast menu it looks like the "today" forecast date is offset and shows it as one date before yet the weather on it is accurate.
![Screenshot_20240917-001211](https://github.com/user-attachments/assets/1c8d6faf-1cab-40ad-8a61-d138a680d138)
![markup_1000000408](https://github.com/user-attachments/assets/85d158d9-aff3-4f1e-9669-e970ae9751fa)
![markup_1000000407](https://github.com/user-attachments/assets/9b47034f-0226-4943-8dc0-07e29f117489)

**Comment by PranshulGG** [comment]
Oh, now I get it. Maybe it's pulling the wrong timezone and showing the past forecast instead of the next one due to the difference between the timezone and the current time.

**Comment by PranshulGG** [comment]
Update: I literally tried everything, and it seems to be working fine 😣. I can't get it to show the wrong dates. Are the dates always showing incorrectly for you, or do they get fixed later in the day?

**Comment by PranshulGG** [comment]
> Yeah I think it might be a time zone issue. I looked over it at like 8 pm my time (ET) and I believe it switched over to the correct date.

Well, if that's the case, it's probably an issue with the API, but I'll still see if there's anything I can do to fix it anyway.

**Comment by PranshulGG** [comment]
@Christmaswreath "Can you specify where it's showing NaN° and what background animation you're talking about?

**Comment by PranshulGG** [comment]
@Christmaswreath "Can you specify where it's showing NaN° and what background animation you're talking about?

**Comment by Christmaswreath** [comment]
> @Christmaswreath Can you specify where it's showing NaN° and what background animation you're talking about?

The problem seems to have fixed itself. I will try to keep you updated.

**Comment by Christmaswreath** [comment]
https://github.com/user-attachments/assets/8ad83a9a-9d15-4a90-bdf0-750e50b7fa35

Here is the recording. I clicked where the temperature display was showing NaN°. Also, to further help, on the 14 day forecast section the "more" button doesn't work.

**Comment by PranshulGG** [comment]
'More' isn't a button. Click on a forecast item—it’s just there to show that it’s clickable. I didn’t see any NaN in the recording, so it would be helpful if you could attach a screenshot. Maybe it fixed itself.

**Comment by Christmaswreath** [comment]
The ">" in an app usually indicates a button. I was able to capture the error as a screen recording now. Maybe try setting your time zone to CST to recreate it? [The video](https://photos.app.goo.gl/5tYFzr8gak6yxNA58)

**Comment by PranshulGG** [comment]
It's really hard; even after switching the timezone to CST, I can't recreate it.

**Comment by sarojpanda44** [comment]
I'm seeing correct days in forecast. Today is Thursday and next is shown Friday

**Comment by PranshulGG** [comment]
> I'm seeing correct days in forecast. Today is Thursday and next is shown Friday

This issue seems to be only with the time zones in America, I guess.
