### ISSUE TITLE
Hourly Forecast Shows All Moons/Suns Regardless Of Time

### ISSUE THREAD

**Issue by dxman** [PranshulGG/WeatherMaster#37]
As stated in the description, all hours in the hourly forecast show the same sun/moon icon, based on the current time, rather than corresponding to the indicated hour. For example, the screenshot below was taken at 8PM, and the hours displayed are the middle of the next afternoon:

 ![Screenshot_20240914-200837_WeatherMaster](https://github.com/user-attachments/assets/84f956d0-d893-4355-8e03-7859df7774b7)

This is happening on v1.6.1, but I first noticed it a few days ago, prior to the latest update. Not sure how far back it goes.

**Comment by PranshulGG** [comment]
So, the icons are displaying for night instead of day—is that the issue? May I ask what timezone you're in, if you don't mind sharing?

**Comment by PranshulGG** [comment]
Hey, I’ve finally fixed it, and it will be included in the next update. Looks like I forgot to account for different timezones when calculating the time.

**Comment by dxman** [comment]
Thanks, I'll give it a check once it's released.

Actually, I just noticed that it's working as I expect during the daytime (see screenshot, taken at around 10AM), so maybe it was only a problem when the current time is night? 🤔

![Screenshot_20240915-095219_WeatherMaster](https://github.com/user-attachments/assets/ffa38538-f2ca-4661-a8b8-9b6e3edae4ff)

**Comment by PranshulGG** [comment]
Yeah, after the sun sets, it wasn't calculating the next sunrise time to display the daytime icons properly. I’ve fixed it now, so I'm gonna close this issue.
