### ISSUE TITLE
"Weather alerts" ist not translated

### ISSUE THREAD

**Issue by Stzyxh** [PranshulGG/WeatherMaster#38]
The Phrase "Weather alerts" ist not translated.
Also the phrase "live radar" isn't translated

**Comment by PranshulGG** [comment]
The phrase 'Weather alerts'—do you mean on the alert page or the home page? As for the term you haven't translated, I've added a translation engine that handles some of the translations, but it can change in the future. You can go to POEditor and translate more terms that I've added.

**Comment by Stzyxh** [comment]
> The phrase 'Weather alerts'—do you mean on the alert page or the home page? As for the term you haven't translated, I've added a translation engine that handles some of the translations, but it can change in the future. You can go to POEditor and translate more terms that I've added.

The phrase "weather alerts" on the homepage is alredy translated, but it's still the english phrase. Same goes for "weather radar"

**Comment by Stzyxh** [comment]
> > The Phrase "Weather alerts" ist not translated.
> > Also the phrase "live radar" isn't translated
> 
> I'm pretty sure the live radar is translated.
> 
> ![Screenshot_20240917-203438.png](https://github.com/user-attachments/assets/23e31691-3fdb-4772-88dd-3a14124ccd93)
> 
> 

Oh foult but weather alert is not ![Screenshot_20240917-170748.png](https://github.com/user-attachments/assets/cab19e5d-394d-45a8-aae6-945e59e2cd1c)

**Comment by PranshulGG** [comment]
noted!

**Comment by Stzyxh** [comment]
> noted! 

Thanks
