### ISSUE TITLE
Can't load weather

### ISSUE THREAD

**Issue by zszushi** [PranshulGG/WeatherMaster#4]
An error occurs and the weather cannot be load.
I'm connecting from Japan.
If you need more information, please let me know immediately.
Smartphone:Pixel 7a
OS:Android 14(Security update:August 5, 2024)
![Screenshot_20240822-232830](https://github.com/user-attachments/assets/15e19f07-9135-4535-980a-a29fc446940b)

**Comment by PranshulGG** [comment]
Might be due to api request limit

**Comment by zszushi** [comment]
I'll give it some time and try it
