### ISSUE TITLE
Offline view of last weather

### ISSUE THREAD

**Issue by NikunjKhangwal** [PranshulGG/WeatherMaster#40]
I love everything about the app except one thing, it refreshes everytime when opening and requires internet connection. As someone who's living in 3rd world country with shitty internet this is a major drawback for me. If possible can you make it so we can see the last fetched information offline instead of refreshing everytime? Thank you

**Comment by PranshulGG** [comment]
I was thinking about adding this before, since the app already caches the old data to limit API calls, but the no internet screen still shows up because it needs to load country flags. I'll add this fix in the next version of the app.

**Comment by NikunjKhangwal** [comment]
Thanks so much.

**Comment by faramonius** [comment]
> ...still shows up because it needs to load country flags.

By the way, can't you disable the constant location search on startup? It's unlikely that the weather will change if I move 5 km away :)
Thank you for a bright, unusual program :)

**Comment by PranshulGG** [comment]
@faramonius So you don't want the app to use your location every time it loads? One option is to save your preferred location and set it as your home location in the settings. That way, it won't access your location each time.

**Comment by faramonius** [comment]
@PranshulGG 
That's correct, and I immediately set my city as my home location. But unfortunately a few days later I see the spinning circle again, even though the weather for my city has loaded seemingly correctly. I also see this line in the firewall - I guess it's related to trying to set the location?
WeatherMaster (TCP) -> api.timezonedb.com -> 104.21.93.68
![IMG_20241001_195437](https://github.com/user-attachments/assets/f4e27fcb-d940-440d-8f26-55a2d21ab912)

**Comment by PranshulGG** [comment]
@faramonius It’s fixed now. This was probably because the API limit was exceeded."
