### ISSUE TITLE
Custom API

### ISSUE THREAD

**Issue by FoolishFool4202** [PranshulGG/WeatherMaster#43]
I don't mind the current APIs used as they seem great but I wonder is it's possible to add the feature to have custom api for services like accuweather or the weather channel. I don't really know how accurate Open-meteo and open weather map are for forecasts, pinpoint location, and other kinds of things.

**Comment by PranshulGG** [comment]
AccuWeather is already in the app but hasn't been implemented yet. As for The Weather Channel, I can't use it because it requires a personal weather station to get an API key. For AccuWeather, you'll need to use your own API key since it's not free.

**Comment by FoolishFool4202** [comment]
Does it need more time before it can be implemented? Also that's fine I was planning on buying my own api key. And another thing, is the location accuracy based on the app itself or open weather map/open-meteo?

**Comment by PranshulGG** [comment]
> Does it need more time before it can be implemented? Also that's fine I was planning on buying my own api key. And another thing, is the location accuracy based on the app itself or open weather map/open-meteo? Asking since my location when I move around the state itself and not the city


Probably in the next 1-2 updates. As for the location, it uses the device's GPS to get real-time longitude and latitude, and then the API fetches the location name from the provided coordinates. It exclusively uses Open-Meteo, which I believe is one of the most accurate weather providers, and relies on OpenWeatherMap only for alerts.

**Comment by FoolishFool4202** [comment]
Ohhhhh so Open-meteo is your main source. I just find it weird that it would say the state I'm living in rather than the city itself.

**Comment by PranshulGG** [comment]
Yeah, sometimes it doesn't have the name for a specific location, but it still shows the weather data based on your longitude and latitude, so the city name isn't a big issue.
