### ISSUE TITLE
"Notification bar" and "main temperature" settings are disabled

### ISSUE THREAD

**Issue by ccrowles** [PranshulGG/WeatherMaster#44]
As per title, those two options seem to be disabled?
![Screenshot_20240926-022228_WeatherMaster](https://github.com/user-attachments/assets/21506583-2b6a-42c2-a366-8d718075ab4c)

App version: 1.6.3 (W), installed from FDroid.
Phone model: ZenFone 9
Android version: 14

**Comment by PranshulGG** [comment]
Those haven't been implemented yet.

**Comment by ccrowles** [comment]
Understood, thanks!
