### ISSUE TITLE
Add wind direction and strength to the hourly forecast

### ISSUE THREAD

**Issue by Korb** [PranshulGG/WeatherMaster#46]
I understand that the wind is a complex and fickle thing. Sometimes it dies down to a calm, sometimes there are strong gusts. Each altitude has its own wind.

But as a fisherman, I would find it useful to have an average forecast of the direction and strength of the wind above the surface of the earth.

**Comment by Korb** [comment]
Then perhaps the set of screenshots [on F-Droid](https://f-droid.org/packages/com.example.weathermaster/) should be updated or supplemented. Because when I created the issue I was guided by the assumption that the screenshots reflect the current version of the application and its capabilities. Currently, F-Droid displays a screenshot of the hourly forecast without indicating the wind direction.

**Comment by PranshulGG** [comment]
Noted! Has your issue been solved?

**Comment by PranshulGG** [comment]
@Korb Also, I don’t think my app is on [F-Droid](https://f-droid.org/packages/com.example.weathermaster/).  I can’t seem to find it. It's on [IzzyOnDroid](https://apt.izzysoft.de/fdroid/) 😓
