### ISSUE TITLE
After setting the application language to Russian, the application settings display "Application language: English"

### ISSUE THREAD

**Issue by Korb** [PranshulGG/WeatherMaster#48]
![Screenshot_20240930_172902](https://github.com/user-attachments/assets/91b2b492-28b2-473c-9d5c-1172854bda53)

![Screenshot_20240930_172856](https://github.com/user-attachments/assets/748422d5-40a9-4402-aa40-e7308260b9c1)

WeatherMaster 1.6.3 (W) f-droid

OS version: Funtouch OS 14
Model: Vivo T1 4G (V2153)
Hardware version: MP_0.1
Build number: PD22010F_EX_A_14.2.7.20.W20
Baseband version: S.HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.88
Kernel version: 4.19.157-perf+, 1 Fri Aug 2 14:16:20 CST 2024
Compile time: 2 Aug 2024 09:07:12
Android security update: 1 August 2024
Google Play system update: 1 August 2024
Software parameter update: 22 August 2024

**Comment by PranshulGG** [comment]
Just restart the app after setting the language.
