### ISSUE TITLE
High refresh rate support

### ISSUE THREAD

**Issue by MrRayeen** [PranshulGG/WeatherMaster#50]
Started using the app, immediately noticed the lag from 120 to 60. I would gladly make it my main weather app if it supports a high refresh rate.

**Comment by PranshulGG** [comment]
So is your phone adjusting the app from 120Hz to 60Hz, or is it just laggy?

**Comment by MrRayeen** [comment]
> So is your phone adjusting the app from 120Hz to 60Hz, or is it just laggy?

Adjusting. I said 'lag' as an app experience, because the phone would just dial down the refresh rate.

**Comment by PranshulGG** [comment]
Right, I'll see what's wrong and fix it in the next version, since it's working fine on the devices I've tested.

**Comment by MrRayeen** [comment]
> Right, I'll see what's wrong and fix it in the next version, since it's working fine on the devices I've tested.

For more reference I'm using an iQOO phone.
Looking forward to seeing it getting fixed 😊
