### ISSUE TITLE
Infinite Loading icon, location will not load, even when trying manually

### ISSUE THREAD

**Issue by ppppaup** [PranshulGG/WeatherMaster#51]
Hey, Amazing and beatiful app, but I'm afraid I cannot use it right now... The Location permissions are set to precise, location is on, but the location itself will not load, even if I try to type it in manually, or pinpoint it from the map screen. Please help :))
![WhatsApp Image 2024-10-01 at 21 24 34_31076a31](https://github.com/user-attachments/assets/b78f4c58-afe2-4468-a7cd-fcb88c39410c)
![WhatsApp Image 2024-10-01 at 21 24 34_cd1b33da](https://github.com/user-attachments/assets/7d3ce078-5a74-47d6-81a4-6fa67367dd49)

**Comment by PranshulGG** [comment]
It’s fixed now. This was probably because the API limit was exceeded.
