### ISSUE TITLE
Few enhancements and suggestions


### ISSUE THREAD

**Issue by freyjasasi** [PranshulGG/WeatherMaster#52]
### App is really great. Thanks for you work👍 

1. Moon phase tile did not open like other tiles like humidity and others
2. Manual location search does not have all location information. 
3. Not able to save current location. If I open app and every time I need to turn on location 
4. Rader background must have light and dark mode
5. Add m/s for wind 
6. In hourly precipitation forecast it shows how much rain but no probability percentage. Like 10% chance for 0.2 mm like this, it shows only rain amount

**Comment by PranshulGG** [comment]
These issues are fixed and will be included in the next version. However, the moon phase widget doesn’t have any extra data to display on the next page. I was thinking of adding a moon phase forecast there, but I still need to find a good free API for that. As for the location info, what do you mean by 'it doesn’t have all the info'? If you're unable to find your location, you can try typing it more specifically, including the city, state, or country. Let me know if you need any help.

**Comment by freyjasasi** [comment]
Location info for my village. It's not present when I search

**Comment by PranshulGG** [comment]
Hmm, I know about this issue. It’s probably because the API does have your location, but the data doesn’t have a name for it, so it only shows the state and country. I'll take a look and fix it.

**Comment by freyjasasi** [comment]
1 more I noticed now. Cause I am using from .yesterday night after seen the app in how to men video

UV in home page shows 2 but if I open it shows 3

**Comment by PranshulGG** [comment]
The page actually shows the Highest avg. Index

**Comment by freyjasasi** [comment]
Map is not loading when the location is not turned on in the app first launch

**Comment by PranshulGG** [comment]
That's because you haven't saved or searched for any location, so it doesn't have a location to place the pointer. You need to search for a location first.

**Comment by freyjasasi** [comment]
Please add a option to save current location

**Comment by Stzyxh** [comment]
> Please add a option to save current location 

When you are searching for a location, then it will be shown and when you look right there should be a save button

**Comment by freyjasasi** [comment]
Yes that is for location which comes in search. As i already me tinned my location does jot have a name in api dB you are using 

In that case i need option to save current location

**Comment by PranshulGG** [comment]
Even if the location isn’t exactly yours, it’s showing the nearest one. It doesn’t affect the weather data because the weather is fetched using your latitude and longitude. Then, based on those coordinates, it fetches the location name. It’s possible the city isn’t in the database, or it’s pulling the name through the coordinates. It won’t affect the weather. If you're okay with it, can you provide the city you’re trying to search for?

**Comment by freyjasasi** [comment]
If I can't save current location and my place name is not present in search because of this i have to turn on location every time. It's not saving current location by itself and no option to save

**Comment by freyjasasi** [comment]
If I can't save current location and my place name is not present in search because of this i have to turn on location every time. It's not saving current location by itself and no option to save

**Comment by PranshulGG** [comment]
In the next version, I’ve added the option to search for locations using the pin code. Maybe that will work for you.

**Comment by PranshulGG** [comment]
If that's your only issue, you don’t need to turn on your location every time you open the app.

**Comment by freyjasasi** [comment]
Ok, may be. I will check. But please add an option to save the current location along with its coordinates

**Comment by PranshulGG** [comment]
Yep 👍.

**Comment by freyjasasi** [comment]
Thanks. Live rader is super accurate, though. The weather forecast says no rain but in rader it shows

**Comment by PranshulGG** [comment]
Yep, I have fixed everything that was requested and that I could fix. I have also added one more search provider, which may help.
