### ISSUE TITLE
Changing visibility unit 

### ISSUE THREAD

**Issue by Alexanderthegreat2** [PranshulGG/WeatherMaster#54]
I have went in my setting and changed it from km to miles but for some reason it will not change it just show km 
![Screenshot_20241003_065941_WeatherMaster](https://github.com/user-attachments/assets/4f69b812-e2c9-4025-92e0-eeccf2444b6b)
![Screenshot_20241003_065935_WeatherMaster](https://github.com/user-attachments/assets/e189c82e-52be-4b5c-af6f-5da76576d9b9)

**Comment by PranshulGG** [comment]
It looks like I somehow forgot to add the function to convert kilometers to miles. I don't know how I didn't notice it until now.
