### ISSUE TITLE
Accuweather api 

### ISSUE THREAD

**Issue by freyjasasi** [PranshulGG/WeatherMaster#58]
![Screenshot_20241005_150736_Brave.jpg](https://github.com/user-attachments/assets/6044c3f2-785f-4491-bd76-04fd2def5728)

What is the correct way to configure. I tried other and mobile app and other and other too. Not working 

Please provide some info on this

**Comment by PranshulGG** [comment]
You can check this:

https://developer.accuweather.com/getting-started

If you still need help, just ask.

**Comment by freyjasasi** [comment]
It's not working for me. Please tell me what fields I need to put

**Comment by PranshulGG** [comment]
Can you provide screenshots of the fields so I can assist you better?

**Comment by freyjasasi** [comment]
It's in my first post

**Comment by freyjasasi** [comment]
I got errors, api not working all the time

**Comment by PranshulGG** [comment]
> I got errors, api not working all the time

Did you get the api key?

**Comment by freyjasasi** [comment]
Yes I have the api key

**Comment by PranshulGG** [comment]
> Yes I have the api key

Well, I have to take a look to see what the problem is. I’ll let you know.

**Comment by freyjasasi** [comment]
Ok. But when you tested what fields you configured in edit section of developer.accuweather.com

**Comment by PranshulGG** [comment]
I just saw that in the release version, I accidentally switched the latitude and longitude. Since I have different code for debug and release, it sometimes gets messed up😓.  And i tested it on the debug and i don't think fields matter to make it work.
