### ISSUE TITLE
App does not load location's data/content

### ISSUE THREAD

**Issue by TB1333** [PranshulGG/WeatherMaster#6]
I may open the settings, I also see my correctly recognized location. 
But when I want to select the location from the 'list' nothing happens.
There's just a black screen with the progress bar on top of the screen running for all eternity. Same behaviour when I look up for a location on the map.

What I already tried:
- I waited for a matter of minutes
- I deactivated the battery optimization
- I granted any possible permissions
- I cleared the app cache and app data
- I re-installed the app

Manufacturer: Realme 
Device model: RMX3516
Android 13

**Comment by Illumes** [comment]
I also have this issue in the latest release build. No weather information is loading so doesn't seem to be getting the API data.

App version I have is:
1.4.8 (W)

**Comment by PranshulGG** [comment]
> I may open the settings, I also see my correctly recognized location. 
> But when I want to select the location from the 'list' nothing happens.
> There's just a black screen with the progress bar on top of the screen running for all eternity. Same behaviour when I look up for a location on the map.
> 
> What I already tried:
> - I waited for a matter of minutes
> - I deactivated the battery optimization
> - I granted any possible permissions
> - I cleared the app cache and app data
> - I re-installed the app
> 
> Manufacturer: Realme 
> Device model: RMX3516
> Android 13

The issue might be that the API request limit was exceeded, and you need to save the location from the search before displaying it in the list

![Screenshot_20240823-075902.png](https://github.com/user-attachments/assets/3531086c-20ab-42c5-ac06-6fc285a8cfd2)

![Screenshot_20240823-075913.png](https://github.com/user-attachments/assets/44d84d69-a45c-498f-87cb-6fc24c9e9d68)

**Comment by TB1333** [comment]
Thanks for your prompt feedback.

It doesn't make any difference if I save the location beforehand or not. 
It's also independent from the type of location selection (selecting from search bar or from saved list). 
It does not matter if the app is in the foreground or in the background while loading. 

The location permission is granted. Location service is activated.

**Comment by PranshulGG** [comment]
> Thanks for your prompt feedback.
> 
> It doesn't make any difference if I save the location beforehand or not. It's also independent from the type of location selection (selecting from search bar or from saved list). It does not matter if the app is in the foreground or in the background while loading.
> 
> The location permission is granted. Location service is activated.

It seems to be working fine on the devices I've tested. Could you please provide the details of the device you're using? That will help me.

**Comment by PranshulGG** [comment]
> > Thanks for your prompt feedback.
> > It doesn't make any difference if I save the location beforehand or not. It's also independent from the type of location selection (selecting from search bar or from saved list). It does not matter if the app is in the foreground or in the background while loading.
> > The location permission is granted. Location service is activated.

**Comment by PranshulGG** [comment]
> > > Thanks for your prompt feedback.
> > > It doesn't make any difference if I save the location beforehand or not. It's also independent from the type of location selection (selecting from search bar or from saved list). It does not matter if the app is in the foreground or in the background while loading.
> > > The location permission is granted. Location service is activated.

Hey, I found the issue! I accidentally removed the location code that requests the necessary permission. I'll be updating the app with the fix in the new version shortly. 😓

**Comment by TB1333** [comment]
Thanks for the feedback. I will test the updated version and keep you posted.

**Comment by dxman** [comment]
Confirmed, I was experiencing the same issue yesterday, upgraded to 1.5.0, and it is now working for me.

**Comment by PranshulGG** [comment]
Thanks for the update 👍
