### ISSUE TITLE
Problem with updating app

### ISSUE THREAD

**Issue by NT457** [PranshulGG/WeatherMaster#60]
When updating the app to v1.6.4 it gives me this pop-up
![Screenshot_20241006-110356](https://github.com/user-attachments/assets/7afcb38f-6b5d-4feb-94c2-d260bf1ca30c)
It doesn't allow me to update the app for some reason ;-;

**Comment by PranshulGG** [comment]
The fix is to delete the previous version of the app and then install the new one because the app name was changed.

**Comment by NT457** [comment]
> The fix is to delete the previous version of the app and then install the new one because the app name was changed.

Thnx that fixed it :D
