### ISSUE TITLE
Package has conflicts issue 

### ISSUE THREAD

**Issue by itz-rj-here** [PranshulGG/WeatherMaster#62]
![Screenshot_2024-10-08-15-35-31-565_com.google.android.packageinstaller.png](https://github.com/user-attachments/assets/94a3e24f-7e23-4166-a0b6-6ee02c38100c)

**Comment by PranshulGG** [comment]
Delete the previous version of the app and then install the new one.

**Comment by itz-rj-here** [comment]
It worked.. Thanks, but it should be updated by the package installer. I hope it will be fixed soon.
