### ISSUE TITLE
Conflict with new version 

### ISSUE THREAD

**Issue by Stzyxh** [PranshulGG/WeatherMaster#63]
This and the last update were having the problem that there was a conflict. I couldn't install it. I'm not very in in App Development but I think you builded differently. For the same reason you cant update a github or izzyondroid app with a  F-Droid Apk.

**Comment by PranshulGG** [comment]
Yeah, the current version was the fix for that. Now you can update it from the f droid

**Comment by Stzyxh** [comment]
> Yeah, the current version was the fix for that. Now you can update it from the f droid 

But there isn't any f droid download

**Comment by PranshulGG** [comment]
> izzyondroid

izzyondroid

**Comment by Jayc965** [comment]
This issue still exists. I manually updated this application with apk file from here(GitHub), and still faced the same issue. I previously had downloaded 1.6.4 from GitHub as well.

**Comment by PranshulGG** [comment]
@Jayc965, version 1.6.5 (W) fixed that issue, so you can now update it from IzzyOnDroid.
