### ISSUE TITLE
Tab title Weather alerts is not translated

### ISSUE THREAD

**Issue by Quiwy** [PranshulGG/WeatherMaster#66]
For the moment, weather alerts are not in the language of the phone.

Is there a way to change this ? The all app.is in the good language except this.

![Screenshot_20241008-203736_Weather Master](https://github.com/user-attachments/assets/e79d1f9c-c535-4b91-926b-ccc0acc74ad8)

This occurs event if météo France provides French versionof the text.

**Comment by PranshulGG** [comment]
Well, I can't really do anything about the language used for the alert, as it depends on how it was sent and your location.

**Comment by Quiwy** [comment]
Well, I guess it depends on where you're getting the alerts from, as the Meteo France provider offers them in both English and French.

However, the title of the tab could maybe be translated as well ?

![image](https://github.com/user-attachments/assets/df22e2ba-52f1-4e65-ae5e-a2ba5d2d4b05)


I guess French version could be retrieved from[ Meteo France api](https://portail-api.meteofrance.fr/web/fr/api/DonneesPubliquesVigilance) directly, but it can be a huge development. Maybe should I fill another issue with indicating that this is a feature request, and keep this issue for the tab title ?

**Comment by PranshulGG** [comment]
Yep 👍
