### ISSUE TITLE
Please make the "New App Version is available!" prompt non-persistent.

### ISSUE THREAD

**Issue by FastCar3000** [PranshulGG/WeatherMaster#68]
### Please make "New App Version Available" Prompt Non-Persistent

Is it possible that whenever there's a new update, the *"New App Version is available!"* prompt is not persistent, but rather fades away after a few seconds? 

Currently, it just sits there and is very distracting if I'm not intending to update right away.

![Screenshot_20241009-204034_Weather Master](https://github.com/user-attachments/assets/d9c2da75-3bd0-432e-9213-32a38081d984)

**Comment by PranshulGG** [comment]
I think I should add an option in the settings to make the message either disappear after some time or stay visible.

**Comment by FastCar3000** [comment]
Yes please do. Thank you. 🙏🏾
