### ISSUE TITLE
Moon-data the only "widget"-style element missing an icon & it's not a link, for further info-card redirection

### ISSUE THREAD

**Issue by Montell2099** [PranshulGG/WeatherMaster#69]
![Screenshot_20241010-005531](https://github.com/user-attachments/assets/048c5984-7288-4dee-9786-87314c8f3371)

**Comment by PranshulGG** [comment]
There isn't enough space for the icon, so the moon phase name is displayed instead. There isn't any extra information to show on a separate page, so while there will be a moon forecast, I still need to find a free API.

**Comment by Montell2099** [comment]
> There isn't enough space for the icon, so the moon phase name is displayed instead. There isn't any extra information to show on a separate page, so while there will be a moon forecast, I still need to find a free API.

I'd think a moderately sized & simple moon-icon could easily fit — if only the current moon-phase description just got shifted a couple of px to the right (_depending on the moon-phase-string's longest possible amount of characters_).

Even the icon for "pressure" is a bit on the smaller side, compared to every other icon that is very distinct & bold in nature. When I'm back at my PC I could update this post with a quick Photoshop-sketch of how I'd like to see things.

Would be nice as well for users to learn/understand more about what that moon-data _**exactly**_ tells the user — especially since the layout isn't customizable. Users may question why they should care about the moon-phase to such a degree that it is placed in the very top-row amongst the "widget-style" boxes.

It's not a bad design at all as it currently stands, but who doesn't love when the design language & functionally is consistent through-and-through. But I totally understand if there's no readily available API that could provide that sort of data for free.

**Comment by PranshulGG** [comment]
I understand, and I will consider making these changes, as well as creating a customizable layout for the widgets.

**Comment by PranshulGG** [comment]
@Montell2099  Well, I added the icon, but it just looks ugly.

![Screenshot 2024-10-13 212511](https://github.com/user-attachments/assets/105e50bf-83fb-4f61-9355-5a8fa310c1c8)
