### ISSUE TITLE
Today and Hourly Precip. tabs not loading

### ISSUE THREAD

**Issue by Illumes** [PranshulGG/WeatherMaster#7]
The tabs for today and hourly precipitation consistently load.
![Screenshot_20240823-131542](https://github.com/user-attachments/assets/fe76c362-fb74-4503-95ef-e8f8dde95ac1)

**Comment by PranshulGG** [comment]
> The tabs for today and hourly precipitation consistently load. ![Screenshot_20240823-131542](https://private-user-images.githubusercontent.com/92645885/361012567-fe76c362-fb74-4503-95ef-e8f8dde95ac1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzQxMTMsIm5iZiI6MTcyNDQzMzgxMywicGF0aCI6Ii85MjY0NTg4NS8zNjEwMTI1NjctZmU3NmMzNjItZmI3NC00NTAzLTk1ZWYtZThmOGRkZTk1YWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE3MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZjNiOTljMzAyMGNjZjU3YWUzYjZhNGZhNGNiOTE5MGVjMjRmYjU0N2UzNDMzZmY4NzViM2JjZmFiMWEzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C-IfazK0pxLaAWmL4YwbefSiCRc7RV41sj63e9aJqW4)

It's possible that the API requests for the hourly forecast exceeded the limit. I'm working on handling API requests better, but it's going to take some time. By the way, it will work again once the API resets

**Comment by PranshulGG** [comment]
> Ah okay, that's what I thought, thanks. Will you be implementing caching anytime soon?

Yep thats the next step
