### ISSUE TITLE
Issue in weather animation 

### ISSUE THREAD

**Issue by freyjasasi** [PranshulGG/WeatherMaster#70]
animation speed gets increased when I press hour data again and again
![Screenshot_20241010_181130_Weather Master.jpg](https://github.com/user-attachments/assets/161981cb-14b4-4ade-8977-0ebb1b453a6f)

**Comment by PranshulGG** [comment]
Yeah, I looked into it, and it seems like it’s calling the canvas function every time the animation updates, which is duplicating the animation! This will be fixed in the next version.
