### ISSUE TITLE
Clothing recommendations seems incorrect

### ISSUE THREAD

**Issue by freyjasasi** [PranshulGG/WeatherMaster#73]
![Screenshot_20241015_212835_Weather Master.jpg](https://github.com/user-attachments/assets/7f4e73be-8668-4d5a-8104-54e7c56f07cc)

**Comment by PranshulGG** [comment]
It suggests based on the current temperature, not the daily average.

**Comment by PranshulGG** [comment]
You might need to re-download and install the app—I’ve fixed a few things with the weather report.

**Comment by freyjasasi** [comment]
Still same. Even considering the current temperature, it's 25, and it's definitely not warm

**Comment by PranshulGG** [comment]
Right, it looks like I’ll have to base the clothing suggestions on the high and low temperatures and calculate the average.
