### ISSUE TITLE
strings not translated 

### ISSUE THREAD

**Issue by Stzyxh** [PranshulGG/WeatherMaster#74]
### Srings not tranlsated ( Uv index and air pollotion text)
![fairphone_screenshot](https://github.com/user-attachments/assets/9e4ddaa3-3c7f-4b9e-abc7-2545cda5e267)

**Comment by PranshulGG** [comment]
@Stzyxh  Restart the app

**Comment by Stzyxh** [comment]
> @Stzyxh  Restart the app

Lol. Worked
