### ISSUE TITLE
12hr format missing in live rader

### ISSUE THREAD

**Issue by freyjasasi** [PranshulGG/WeatherMaster#76]
In live rader, it has 24-hour format even though in settings it is set to 12hr

**Comment by PranshulGG** [comment]
I’m not sure, but I checked and it worked fine. Maybe try setting it to 24-hour format and then back to 12-hour. It might be an issue with the saved value.

![Screenshot_20241017-160232.png](https://github.com/user-attachments/assets/cf822862-e8b6-49a8-811a-8186a250c42f)

**Comment by PranshulGG** [comment]
> It's not working. I tried switching and restarting app but no use. Still, it's in 24-hour format only.

Is this issue only with the radar, or does it affect the whole app? Maybe try clearing the app data.

**Comment by freyjasasi** [comment]
The rest of the app is fine. I tried clearing cache, too, after changing the time format

**Comment by PranshulGG** [comment]
> The rest of the app is fine. I tried clearing cache, too, after changing the time format

Did you tried clearing the app data?

**Comment by freyjasasi** [comment]
I did a fresh install

**Comment by PranshulGG** [comment]
> I did a fresh install of v1.6.7

Yeah, but it doesn’t clear your app data. I don’t know how to reproduce the issue. It’s working fine on my end, and the code seems to be fine too.

**Comment by freyjasasi** [comment]
Hmm OK. I will check once

**Comment by PranshulGG** [comment]
@freyjasasi Close the issue if its solved.
