### ISSUE TITLE
Weather alerts not working anymore

### ISSUE THREAD

**Issue by Quiwy** [PranshulGG/WeatherMaster#77]
Since last update, there is no weather alert showing.

![Screenshot_20241017-130117_Weather Master](https://github.com/user-attachments/assets/5ce03c44-9368-45dd-b9b9-737089888eca)

There should be some alerts for this location.
For example, in breezy weather :

![Screenshot_20241017-130225_Breezy Weather](https://github.com/user-attachments/assets/c91f752f-19e3-4e72-8cac-96aa3e0585c6)

**Comment by PranshulGG** [comment]
Yep, it’s a bug. I’m going to push a new version in a few hours, which will fix this issue. I noticed the weather report is either not showing or it’s incorrect as well.

**Comment by Quiwy** [comment]
Still don't have weather alert in 1.6.7 😞

**Comment by PranshulGG** [comment]
Might be because of API limit is exceeded. You have to wait until it resets
