### ISSUE TITLE
Settings to use system font or dismiss update reminder doesn't persist

### ISSUE THREAD

**Issue by Cris-Edmundson** [PranshulGG/WeatherMaster#78]
When I: 

1. enter settings
2. turn on the settings to use the system font and dismiss the update reminder after 5 seconds
3. then leave settings via the back button in the top left or bottom system navigation bar
4. And then return to settings

The two settings are back in the off position

**Comment by Cris-Edmundson** [comment]
Upon tinkering with it more, this behaviour may have been caused by clearing the cache? The system font setting doesn't switch to my system font so I tried clearing the cache and then noticed the setting wasn't persisting.

I was able to fix the issue by clearing the app storage and setting the app up again, but I can't recreate the behaviour where the settings didn't persist, and I hadn't checked whether other settings were affected. Not sure why I had this problem, but unless other people are experiencing the issue or can comment on what conditions result in the settings not persisting, maybe this can just be ignored. Just figured I'd open an issue so there's record of it somewhere

Thanks for all your hard work on the app! the UI is phenomenal and I really appreciate having a Foss weather app that has radar (and looks lovely!)

**Comment by PranshulGG** [comment]
I just checked the code and saw that the function applying the font is duplicated, which is causing the error. That’s why it isn’t persisting. The system font is still an issue since there’s no way to get it through JavaScript, but I’ll find another way to make it work.
