### ISSUE TITLE
What about having a weather report like accuweather?

### ISSUE THREAD

**Issue by freyjasasi** [PranshulGG/WeatherMaster#79]
Like 
In morning 
It will show for morning and noon
In noon
It will show noon and evening 
In evening 
It will show the evening and tonight 
In night 
It will show tonight and tomorrow overall 

It makes more granular reports and more accurate, and it changes over day progress 

To see for that day, click expand downarrow as always

**Comment by PranshulGG** [comment]
The weather report gives an overview of the whole day, but I can definitely adjust some details as the day progresses. And aslo adding the weather report to the forecasts.
