### ISSUE TITLE
Won't go beyond startup location setup

### ISSUE THREAD

**Issue by Veraellyunjie** [PranshulGG/WeatherMaster#82]
Location denied, wanna pick manually, but it displays loading indefinitely.
There is an icon at top-right corner that leads to "Pick a location", but the page is empty.
Version 1.6.8 (W) from IzzyOnDroid, Android 10

related:
https://github.com/PranshulGG/WeatherMaster/issues/1
https://github.com/PranshulGG/WeatherMaster/issues/8

**Comment by PranshulGG** [comment]
If you want to use it without accessing your location, just search for your location or enter its longitude and latitude, then hit the save button. Go to settings and set it as your home location.

**Comment by PranshulGG** [comment]
The 'Pick a location' option is a map, and it won’t load until you have a location saved.
