### ISSUE TITLE
Is AccuWeather available or a pending feature?

### ISSUE THREAD

**Issue by JesseRacine** [PranshulGG/WeatherMaster#83]
The AccuWeather option is grayed out and is not selectable for me. Is this an upcoming feature, or is there something I need to do to activate it? Thanks.

**Comment by PranshulGG** [comment]
> The AccuWeather option is grayed out and is not selectable for me. Is this an upcoming feature, or is there something I need to do to activate it? Thanks.

Has some bugs, so it's pending for a fix.
