### ISSUE TITLE
UV Index Incorrect on high-UV days

### ISSUE THREAD

**Issue by BenDundon** [PranshulGG/WeatherMaster#84]
I live in a place with a lot of _very_ sunny days, and I've noticed that on days where I would expect that it would be a 9 or a 10, WeatherMaster instead says 1 (even at times when the sun is highest). As far as I can tell, this doesn't _seem_ to be an issue with the OpenMeteo source data, as it seems to be giving me the correct expected amount when I use the API directly (though it should be noted, I'm doing this retroactively, so OpenMeteo may still be the problem).

**Comment by PranshulGG** [comment]
It doesn’t use OpenMeteo for UV index. Are you seeing the wrong index during the daytime or nighttime?

**Comment by BenDundon** [comment]
During the daytime, yeah, usually in the peak hours (11:00-15:00)

**Comment by PranshulGG** [comment]
> During the daytime, yeah, usually in the peak hours (11:00-15:00)

Right, is it the current UV index or the forecast? For context, you can click on the current UV index container, which gives you the average for the day, sourced from OpenMeteo. If that's incorrect too, let me know, and I can switch the API to OpenMeteo.

**Comment by BenDundon** [comment]
In true ironic fashion, the weather here has taken a turn for the worse. I will update this issue again when we have another sunny day and I can confirm for you, but you can probably leave it closed until then to keep it out of the way.

**Comment by PranshulGG** [comment]
> In true ironic fashion, the weather here has taken a turn for the worse. I will update this issue again when we have another sunny day and I can confirm for you, but you can probably leave it closed until then to keep it out of the way.

@BenDundon Right, I have changed the UV index provider to OpenMeteo, which will update every hour.

**Comment by BenDundon** [comment]
OK, we've had a couple of absolute scorchers over the past couple of days and it's seemed accurate every day, so I'd say that fix worked, thanks!

**Comment by PranshulGG** [comment]
> OK, we've had a couple of absolute scorchers over the past couple of days and it's seemed accurate every day, so I'd say that fix worked, thanks!

Thats nice!
