### ISSUE TITLE
Constant error on start

### ISSUE THREAD

**Issue by owen-the-kid** [PranshulGG/WeatherMaster#86]
i tried reopening,
reinstalling and waiting a day but didnt work
![Screenshot_20241021-105241.png](https://github.com/user-attachments/assets/2e4ffef5-0f6b-4157-83ef-7110c4bb7a43)

**Comment by PranshulGG** [comment]
Is location permission denied?

**Comment by owen-the-kid** [comment]
i have it on precise and its accepted

**Comment by PranshulGG** [comment]
I can't reproduce this issue; it seems to work fine on my end. Maybe try denying the permission and manually searching for the location.

**Comment by owen-the-kid** [comment]
it works on nyc
![Screenshot_20241021-120921.png](https://github.com/user-attachments/assets/183bebd1-b7cd-4b1a-8349-e3a9527b9b23)

i think its my town

**Comment by owen-the-kid** [comment]
it starts with a (') so maybe that could be an issue

**Comment by PranshulGG** [comment]
Well, the location name doesn't really matter since the weather is fetched using longitude and latitude. You can search for your town with its name or its longitude and latitude, save it, and then go to the settings to set it as your home location. In the meantime, I'll try to fix it if I find anything wrong.

**Comment by gargamel17** [comment]
Same issue, previous version works fine

**Comment by PranshulGG** [comment]
I'm assuming it's an issue with specific locations. If you're okay with it, could you let me know which location you're having this error with?

**Comment by gargamel17** [comment]
Crisnée, in Belgium

Le 21 octobre 2024 12:59:13 UTC, Pranshul ***@***.***> a écrit :

**Comment by owen-the-kid** [comment]
> I'm assuming it's an issue with specific locations. If you're okay with it, could you let me know which location you're having this error with?

can i dm it to you in discord or telegram?

**Comment by PranshulGG** [comment]
> > I'm assuming it's an issue with specific locations. If you're okay with it, could you let me know which location you're having this error with?
> 
> can i dm it to you in discord or telegram?

discord is fine

**Comment by gargamel17** [comment]
I use none of these, sorry, out of social networks

Le 21 octobre 2024 13:32:16 UTC, OwenTheKid ***@***.***> a écrit :

**Comment by PranshulGG** [comment]
Well, I'm going to push a new update. I’ve made a few changes and added an error prompt that will display any error text if available since I really couldn’t reproduce the issue.

**Comment by PranshulGG** [comment]
fixed 1.7.0

**Comment by bohaoy** [comment]
I just updated and I'm also having this error
![Screenshot_20241021-161613.png](https://github.com/user-attachments/assets/26d1718d-cf50-4372-9e32-5885e62fdae5)
