### ISSUE TITLE
[Suggestion] Change animation header

### ISSUE THREAD

**Issue by frankh93** [PranshulGG/WeatherMaster#88]
![Picsart_24-10-21_13-52-45-365](https://github.com/user-attachments/assets/5b3adf16-1e60-4c69-9db6-59cca31c2f22)

Well, I don't know if anyone else agrees but I think the way the header/frog image moves up is a bit weird as it gets smaller as gets up. I think the proper should be just be pushed up with the other content without making it smaller. I don't know if my explanation is fine, but I think you can get what I mean.

Also, tried to help with the missing translations on Poeditor but it says the characters has reached its limit or something like that. Thank you beforehand for reading this.

**Comment by PranshulGG** [comment]
It was like that in the older version, but I couldn’t get it to work smoothly—it kept messing up the scrolling. I might give it another shot though, and see if I can make it work. As for the strings you're trying to translate, maybe the limit's been hit. I’ll probably need to remove some older translations.
