### ISSUE TITLE
Add persian language 

### ISSUE THREAD

**Issue by l3lack-eyes** [PranshulGG/WeatherMaster#89]
I am reaching out to express my interest in contributing to your project by adding Persian language support. However, I noticed that Persian is currently not available in the list of supported languages.

As a native Persian speaker, I believe adding this language would be highly beneficial to Persian-speaking users and would enhance the accessibility of your project. I would be happy to collaborate with your team to implement this feature.![Screenshot_2024-10-22-21-20-00-044_com.brave.browser.jpg](https://github.com/user-attachments/assets/8706085b-242e-4e04-9622-6dd0dd44a312)

**Comment by PranshulGG** [comment]
@l3lack-eyes I noticed that you submitted two pull requests that both aim to add Persian ("fa") to langs.js. Could you clarify if there are any differences between them, or do you have a preferred PR that I should merge?

**Comment by l3lack-eyes** [comment]
Hi
No the second commit's code is cleaned using prettier but first one is not.
