### ISSUE TITLE
Day Length

### ISSUE THREAD

**Issue by Illumes** [PranshulGG/WeatherMaster#9]
I have checked day length for multiple days and it never seems to show up.

![share_4391492804004612112](https://github.com/user-attachments/assets/9e90317c-2f6c-4f98-a9e1-fe8549f9be4e)

**Comment by PranshulGG** [comment]
> I have checked day length for multiple days and it never seems to show up.
> 
> ![share_4391492804004612112](https://github.com/user-attachments/assets/9e90317c-2f6c-4f98-a9e1-fe8549f9be4e)
> 

I do know about this issue. Sometimes the API doesn't provide day length data for certain locations. In the next version, I'm planning to switch some APIs to Open-Meteo.

**Comment by Illumes** [comment]
Ah okay, also in the latest release do you have an issue where on first launch of the app no data will load unless you manually refresh.

**Comment by PranshulGG** [comment]
> Ah okay, also in the latest release do you have an issue where on first launch of the app no data will load unless you manually refresh.

Yep, I messed up a few things in the latest version, but I'm fixing everything in the next one.
