### ISSUE TITLE
Mix up of german/english in weather description

### ISSUE THREAD

**Issue by rak-rak** [PranshulGG/WeatherMaster#92]
Hi, languages are mixed through several app versions, last version 1.7.3

See red rectangle in screenshot.

![Screenshot_20241023_150815_Weather Master](https://github.com/user-attachments/assets/790ae61f-b254-4e4b-ba4e-414ad97e3be0)

Looks (english)
Klarer Himmel (german) 
and (english)
Meistens klar (german) 
throughout the day (english)

Additionally "klarer Himmel" and "meistens klar" are a contradiction.
Instead of "meistens klar" other apps use "überwiegend klar" by the way.

**Comment by Stzyxh** [comment]
> The strings are not translated for the words that are still in English. Regarding the feedback:
> 
> > Additionally "klarer Himmel" and "meistens klar" are a contradiction.
> > Instead of "meistens klar" other apps use "überwiegend klar" by the way.
> 
> It shows those for the most common conditions of the day.

I cant translate."String limit reached". Also some strings are translated in the file but in Poeditor there is shown that they are not translated. (In german)
