### ISSUE TITLE
Can't translate

### ISSUE THREAD

**Issue by ak47m91** [PranshulGG/WeatherMaster#95]
Po Edotor locked me out of the Romainian translation

**Comment by PranshulGG** [comment]
POEditor has some issues, but all the Romanian strings are translated.

**Comment by ak47m91** [comment]
No, it shows me 63%

**Comment by ak47m91** [comment]
There are new ones added

**Comment by PranshulGG** [comment]
Check 
[lang.js](https://github.com/PranshulGG/WeatherMaster/blob/master/app/src/main/assets/langs/langs.js)

**Comment by ak47m91** [comment]
What abt po editor, it was way easier

**Comment by ak47m91** [comment]
What abt po editor, it was way easier

**Comment by PranshulGG** [comment]
I'm thinking to move to weblate

**Comment by PranshulGG** [comment]
POEDITOR has a string limit

**Comment by ak47m91** [comment]
And also issue #92 happens to Romainian also

**Comment by PranshulGG** [comment]
Yea those words aren't added

**Comment by ak47m91** [comment]
Well , is weblate better?

**Comment by PranshulGG** [comment]
Yea, I saw breezy weather uses it too

**Comment by ak47m91** [comment]
And how much will it take to migrate to weblate?

**Comment by ak47m91** [comment]
Yeah

**Comment by PranshulGG** [comment]
I don't really know; haven't tried.
