### ISSUE TITLE
Add Vietnamese language

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#96]
Hey there! Could you please include Vietnamese language? Thanks!

**Comment by PranshulGG** [comment]
> Hey there! Could you please include Vietnamese language? Thanks!

@Tuan1-2-3  You can translate and submit a pull request, or wait until Weblate is ready.

**Comment by Tuan1-2-3** [comment]
OK!

**Comment by Tuan1-2-3** [comment]
Hi! I'm going to make a pull request of Vietnamese translation. Can you help me which file should I translate. I'm working on the 'strings' file (not 'strings.json') in app/src/main/assets/translations/Vietnamese/strings_vi.

**Comment by PranshulGG** [comment]
@Tuan1-2-3 You can translate directly on Crowdin instead of making a pull request.

**Comment by Tuan1-2-3** [comment]
OK! But unfortunately, I have posted my pull request.

**Comment by Tuan1-2-3** [comment]
OK!

**Comment by Tuan1-2-3** [comment]
When will Vietnamese language available?😊

**Comment by Tuan1-2-3** [comment]
Oh, what? I spend my whole day for the translation. I remember that I pressed the 'commit changes' button.

**Comment by Tuan1-2-3** [comment]
OK! So I will translate the app on Crowdin.

**Comment by Tuan1-2-3** [comment]
OK! I have made a pull request after thousands of errors😤🫡. I found that GitHub will create a fork before I can make a pull request.

**Comment by PranshulGG** [comment]
nice

**Comment by Tuan1-2-3** [comment]
@PranshulGG Did I make any mistakes? Let me know, I'm eager to improve!

**Comment by PranshulGG** [comment]
> @PranshulGG Did I make any mistakes? Let me know, I'm eager to improve!

I can't see the full strings in the pull request. It might be because the language isn't fully translated on Crowdin.

**Comment by Tuan1-2-3** [comment]
OK! I'm now working again with Crowdin on my phone (not my computer lol)😊.

**Comment by PranshulGG** [comment]
@Tuan1-2-3 Thank you! Now I can add it to the app, and you'll see it in the next update.

**Comment by Tuan1-2-3** [comment]
It's my pleasure.
