### ISSUE TITLE
Wrong font for weather number 

### ISSUE THREAD

**Issue by sarojpanda44** [PranshulGG/WeatherMaster#99]
The font used for the current weather is different that the app font. Check the style of 1 in 10° and 11° / 6°.

![Screenshot_20241026-205922](https://github.com/user-attachments/assets/87a9cf93-1166-466d-a185-a3e8fe589808)

**Comment by PranshulGG** [comment]
It's a UI preference, but I'd consider it if it looks good.

**Comment by sarojpanda44** [comment]
Can you reopen it?

**Comment by PranshulGG** [comment]
It’s intentional that two different fonts are used: Google Sans and Outfit, each with different font heights.
